--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

_addon.author  = 'Nate';
_addon.name    = 'AutoMog';
_addon.version = '2.0';

require 'common';
require 'imguidef';

local autoutil           = require('autoutil');
-- Shared item-description parser + colored stat-diff renderer. Same lib
-- autoequip's gear_tab uses, so the Status-tab equipment-swap Confirm
-- panel below draws an identical green/red delta strip.
local inv_cache_lib      = require('inv_cache');
local char_profile_cache = require('char_profile_cache');
local icon_cache         = require('icon_cache');
local http_client        = require('http_client');
local json               = require('json');
local loading_overlay    = require('loading_overlay');
local autobox    = require('autobox');
local autoscroll = require('autoscroll');
local autobuy    = require('autobuy');
local autosell   = require('autosell');
local autocraft  = require('autocraft');
local autodrop   = require('autodrop');

-- Shared state + extracted tab modules (the tab split moved each tab's render
-- code into its own sibling file; the main file owns shared state, event
-- wiring, the char selector, and tab dispatch).
local state          = require('automog_state');
local C              = require('automog_common');
local nm_hunter_tab  = require('nm_hunter_tab');
local history_tab    = require('history_tab');
local status_tab     = require('status_tab');
local inventory_tab  = require('inventory_tab');
local transfer_tab   = require('transfer_tab');
local craft_tab      = require('craft_tab');
local ah_tab         = require('ah_tab');

local ui_open       = nil;
local active_tab    = 'Status';
local prev_ui_open      = false;

-- Char selector (foundation for char-scoped automog ops, task #109).
-- state.selected_char defaults to the primary on first render. When changed,
-- inv-read paths re-scope to that char via inv_cache_lib's per-char API
-- (charName, bag_id). Action paths (Transfer / AH / Craft) continue to send
-- raw retail packets that hit the primary's session until their per-tab
-- tasks (#110–#113) land; the dropdown rebases display, not writes, in this
-- foundation step.

local TABS = { 'Status', 'Inventory', 'Transfer', 'Auction House', 'Craft', 'NM Hunter', 'History' };


ashita.register_event('load', function()
    autoutil.tag = 'AutoMog';
    ui_open = imgui.CreateVar(ImGuiVar_BOOLCPP);
    autoutil.send_request_server_ident();
    craft_tab.on_load();
    ah_tab.on_load();
    autosell.on_load();
    autocraft.on_load();
    autobuy.on_load();
end);

ashita.register_event('unload', function()
    if ui_open ~= nil then
        imgui.DeleteVar(ui_open);
        ui_open = nil;
    end
    craft_tab.on_unload();
    ah_tab.on_unload();
end);


local AH_CAT_QUERY_OPCODE  = 0x16F;
local AH_CAT_RESULT_OPCODE = 0x170;
-- Custom singleplayer-fork cross-char transfer packets (task #110, consolidated #233).
-- 0x194 AUTOMOG_TRANSFER carries src/dst char names + bag/slot list so the
-- Transfer tab can move between any two sessioned chars owned by the primary.
-- Inventory-tab "Send to <PC>" now also rides 0x194 (src=self bag → dst=PC's
-- LOC_INVENTORY) since every trade target in singleplayer is owned by sender.
-- The retired packets are: 0x16B BULKXFER (was never fired by this addon —
-- intra-char moves go through 0x194 directly), 0x171 ITEM_TRADE.
local AUTOMOG_TRANSFER_OPCODE = 0x194;
local AUTOMOG_TRANSFER_RESULT = 0x195;
local parse_item_stats; -- forward declaration; assigned below with STAT_MULTI

-- Inventory state (inv_cache, container_caps, inv_loading) lives in libs/inv_cache.lua.

autocraft.get_slots = function(item_id)
    local results = {};
    for slot, entry in pairs(inv_cache_lib.get_bag(0)) do
        if entry.id == item_id and entry.count > 0 then
            table.insert(results, { slot = slot, count = entry.count });
        end
    end
    return results;
end;



ashita.register_event('incoming_packet', function(id, size, data)
    if id == 0x150 then autoutil.check_for_server_ident(id, size, data); return false; end
    if id == 0x152 then autoutil.check_for_relay(id, size, data); return false; end
    if id == 0x186 then autoutil.check_for_alliance_pc_list(id, size, data); return false; end
    if id == 0x19F then autoutil.check_for_job_info(id, size, data); return false; end
    if id == 0x19D then autoutil.check_for_change_job_result(id, size, data); return false; end
    if id == 0x163 then autoutil.check_for_change_look_result(id, size, data); return false; end
    if char_profile_cache.on_incoming_packet(id, size, data) then return false; end

    if inv_cache_lib.on_incoming_packet(id, size, data) then
        -- 0x020 / 0x01E live entirely in the cache; they also drive
        -- autodrop/autobuy state, so dispatch to them after the cache
        -- update so their views are consistent.
        if id == 0x020 then
            autodrop.on_incoming_packet(id, size, data);
            autobuy.on_incoming_packet(id, size, data);
        elseif id == 0x01E then
            autodrop.on_incoming_packet(id, size, data);
        end
        return false;
    end
    if id == AUTOMOG_TRANSFER_RESULT then
        local result = struct.unpack('B', data, 5);
        local moved  = struct.unpack('B', data, 6);
        if result == 0 then
            state.transfer_status = string.format('Transferred %d item(s)', moved);
        elseif result == 1 then
            state.transfer_status = string.format('Partial: %d moved (destination full)', moved);
        else
            state.transfer_status = 'Transfer failed';
        end
        -- After a cross-char move, both src and dst cached inventories are
        -- stale. Re-fetch the two participating chars so the Transfer tab
        -- (and any other tabs reading their bags) reflect the new state.
        if id == AUTOMOG_TRANSFER_RESULT and moved > 0 then
            local left_char  = state.transfer_left_char  or state.selected_char;
            local right_char = state.transfer_right_char or state.selected_char;
            if left_char and left_char ~= '' then inv_cache_lib.send_inv_request(left_char); end
            if right_char and right_char ~= '' and right_char ~= left_char then
                inv_cache_lib.send_inv_request(right_char);
            end
        end
        return false;
    end
    if id == AH_CAT_RESULT_OPCODE then
        -- GP_SERV_COMMAND_AH_CAT_RESULT: PacketData at byte 5
        -- [0]=CatId, [1]=Offset, [2]=Count, [3]=IsLast, [4..]=Entries (8 bytes each: u16 ItemId, u16 Count, u32 MinPrice)
        local cat_id  = struct.unpack('B', data, 5);
        local count   = struct.unpack('B', data, 7);
        local is_last = struct.unpack('B', data, 8);
        if not state.ah_cat_cache[cat_id] then
            state.ah_cat_cache[cat_id] = { items={}, complete=false };
        end
        local entry   = state.ah_cat_cache[cat_id];
        local res_mgr = AshitaCore:GetResourceManager();
        -- Entry size grew from 8 → 12 bytes when we split MinPrice into
        -- separate single/stack fields (server packet 0x170 — without the
        -- split, stack buys quoted the single-listing per-unit price, which
        -- under-bids the stack listing and silently fails server-side).
        for i = 0, count - 1 do
            local base             = 9 + i * 12;
            local item_id          = struct.unpack('H', data, base);
            local single_count     = struct.unpack('B', data, base + 2);
            local stack_count      = struct.unpack('B', data, base + 3);
            local min_single_price = struct.unpack('I', data, base + 4);
            local min_stack_price  = struct.unpack('I', data, base + 8);
            local res   = res_mgr:GetItemById(item_id);
            local name  = '';
            local level = 0;
            local jobs  = 0;
            local stats = {};
            local slots = 0;
            if res then
                if res.Name and res.Name[0] then
                    name = tostring(res.Name[0]):gsub('%z', '');
                end
                level = res.Level or 0;
                jobs  = res.Jobs  or 0;
                slots = res.Slots or 0;
                if res.Description and res.Description[0] then
                    stats = parse_item_stats(tostring(res.Description[0]):gsub('%z', ''));
                end
            end
            if name == '' then name = string.format('Item %d', item_id); end
            table.insert(entry.items, {
                id=item_id, name=name, single_count=single_count, stack_count=stack_count,
                min_single_price=min_single_price, min_stack_price=min_stack_price,
                level=level, jobs=jobs, stats=stats, slots=slots,
                stack_size = (res and res.StackSize or 1),
            });
        end
        if is_last == 1 then
            table.sort(entry.items, function(a, b)
                if a.level ~= b.level then return a.level < b.level; end
                return a.name < b.name;
            end);
            entry.complete = true;
            state.ah_browse_requesting = false;
        end
        return false;
    end
    autobox.on_incoming_packet(id, size, data);
    autoscroll.on_incoming_packet(id, size, data);
    autobuy.on_incoming_packet(id, size, data);
    autosell.on_incoming_packet(id, size, data);
    autocraft.on_incoming_packet(id, size, data);
    autodrop.on_incoming_packet(id, size, data);
    return false;
end);

local function slice(args, from)
    local t = {};
    for i = from, #args do t[#t + 1] = args[i]; end
    return t;
end

ashita.register_event('command', function(cmd, nType)
    local args  = cmd:args();
    local first = args[1] and args[1]:lower() or '';
    if first ~= '/automog' then return false; end

    local sub = args[2] and args[2]:lower() or '';
    -- Bare `/automog` (no args) and `/automog show` toggle the UI the same way
    -- `/automog ui` does. Matches the convention used by /autoequip, /autolot,
    -- /autodps, etc.
    if sub == 'ui' or sub == '' or sub == 'show' then
        if ui_open ~= nil then
            imgui.SetVarValue(ui_open, not imgui.GetVarValue(ui_open));
        end
    elseif sub == 'box'     then autobox.retrieve(state.selected_char);
    elseif sub == 'scrolls' then autoscroll.learn();
    elseif sub == 'drop' then
        local sargs = slice(args, 3);
        if sargs[1] == 'stop' then
            autodrop.on_command({'stop'});
        elseif sargs[1] ~= nil then
            local item_name = table.concat(sargs, ' ', 1);
            local slots = C.find_inv_slots_by_name(item_name);
            if #slots == 0 then
                autoutil.log('AutoDrop', 'No items found matching: ' .. item_name);
            else
                autodrop.queue_drops(slots);
            end
        else
            autoutil.log('AutoDrop', 'Usage: /automog drop <item name>  |  /automog drop stop');
        end
    elseif sub == 'sell' then
        local sargs = slice(args, 3);
        if sargs[1] == 'stop' then
            autosell.on_command({'stop'});
        elseif #sargs >= 3 then
            local quantity  = tonumber(sargs[#sargs]);
            local mode      = sargs[#sargs - 1]:lower();
            local item_name = table.concat(sargs, ' ', 1, #sargs - 2);
            if not quantity or quantity < 1 then
                autoutil.log('AutoSell', 'Invalid quantity.');
            elseif mode ~= 'single' and mode ~= 'stack' then
                autoutil.log('AutoSell', 'Mode must be single or stack.');
            else
                local slots = C.find_inv_slots_by_name(item_name);
                if #slots == 0 then
                    autoutil.log('AutoSell', 'No items found matching: ' .. item_name);
                else
                    autosell.queue_sells(slots, mode == 'stack', quantity);
                end
            end
        else
            autoutil.log('AutoSell', 'Usage: /automog sell <item name> single|stack <quantity>');
        end
    elseif sub == 'craft'   then autocraft.on_command(slice(args, 3));
    elseif sub == 'buy'     then autobuy.on_command(slice(args, 3));
    else
        autoutil.log('AutoMog', 'Usage: /automog ui|box|scrolls|drop|sell|craft|buy [args]');
    end
    return true;
end);

local STAT_MULTI = {
    { 'Accuracy', 'ACC' }, { 'Attack', 'ATK' }, { 'Evasion', 'EVA' },
    { 'Ranged Accuracy', 'RACC' }, { 'Ranged Attack', 'RATK' },
    { 'Magic Accuracy', 'MACC' }, { 'Magic Evasion', 'MEVA' },
    { 'Magic Attack Bonus', 'MAB' }, { 'Magic Defense Bonus', 'MDB' },
    { 'Store TP', 'STP' }, { 'Subtle Blow', 'SB' },
    { 'Double Attack', 'DA' }, { 'Triple Attack', 'TA' },
    { 'Crit hit rate', 'Crit' }, { 'Haste', 'Haste' }, { 'Enmity', 'Enmity' },
};

parse_item_stats = function(desc)
    local s = {};
    if not desc or desc == '' then return s; end
    local def = desc:match('DEF:%s*(%d+)');
    if def then s['DEF'] = tonumber(def); end
    local dmg = desc:match('[Dd]amage:%s*(%d+)');
    if dmg then s['DMG'] = tonumber(dmg); end
    local dly = desc:match('[Dd]elay:%s*(%d+)');
    if dly then s['DLY'] = tonumber(dly); end
    for _, pair in ipairs(STAT_MULTI) do
        local sign, val = desc:match(pair[1] .. '([%+%-])(%d+)');
        if sign and val then s[pair[2]] = tonumber(val) * (sign == '-' and -1 or 1); end
    end
    for stat, sign, val in desc:gmatch('([A-Z][A-Z%d]+)([%+%-])(%d+)') do
        if not s[stat] then s[stat] = tonumber(val) * (sign == '-' and -1 or 1); end
    end
    return s;
end


local TAB_DRAW = {
    Status            = status_tab.draw,
    Inventory         = inventory_tab.draw,
    Transfer          = transfer_tab.draw,
    ['Auction House'] = ah_tab.draw,
    Craft             = craft_tab.draw,
    ['NM Hunter']     = nm_hunter_tab.draw,
    History           = history_tab.draw,
};


local function poll_statuses()
    local function check(source, text, char_name)
        if text ~= state.prev_statuses[source] then
            state.prev_statuses[source] = text;
            state.push_status(source, text, char_name);
        end
    end
    local buy = autobuy.state;
    local buy_text = state.has_status(buy.status) and
        (buy.current_name and buy.current_name ~= ''
            and (buy.status .. ' (' .. buy.current_name .. ')')
            or buy.status)
        or buy.status;
    -- Box-pull tags its char when it was triggered on a non-primary
    -- (task #111 stores the target_name on autobox.state). Transfer reads
    -- the right-side char when set, otherwise the row was intra-char.
    check('Box',      autobox.state.status, autobox.state.target_name);
    check('Buy',      buy_text);
    check('Sell',     autosell.state.status);
    check('Drop',     autodrop.state.status);
    check('Craft',    autocraft.state.status);
    check('Scrolls',  autoscroll.state.status);
    -- Either side can now drive cross-char; surface whichever override is
    -- set (right takes precedence if both, matching the destination-is-meaningful
    -- convention used by the Box badge).
    check('Transfer', state.transfer_status, state.transfer_right_char or state.transfer_left_char);
end

ashita.register_event('render', function()
    -- Advance pending HTTP coroutines (NM Hunter fetches go through this).
    -- See libs/http_client.lua header: each addon must call tick() once per
    -- frame from its OWN render hook, otherwise non-blocking requests
    -- never make progress.
    http_client.tick();
    autodrop.on_render();
    autosell.on_render();
    autocraft.on_render();
    autobuy.on_render();
    poll_statuses();

    -- On UI open transition: lazily ensure the selected char's inventory is
    -- loaded. ensure_inventory is a no-op when the cache is already warm,
    -- so re-opening the UI later in the session is instant. Use the Reload
    -- Inventory button for a force refresh.
    local cur_ui = ui_open ~= nil and imgui.GetVarValue(ui_open) or false;
    if cur_ui and not prev_ui_open and state.selected_char and state.selected_char ~= '' then
        inv_cache_lib.ensure_inventory(state.selected_char);
    end
    prev_ui_open = cur_ui;

    if ui_open == nil or not cur_ui then return; end

    -- Fixed initial size with manual resize handles - NOT AlwaysAutoResize.
    -- AlwaysAutoResize fights nested BeginChild(W, 0) panes: those rely on
    -- a parent-imposed remaining-height to fill, but auto-resize makes the
    -- parent wait on the children's content size, which collapses the
    -- inner lists to a tiny default and clips long content (item lists,
    -- history rows, etc.).
    --
    -- Height tuned to fit the Status tab's left column without scrolling:
    --   name + identity (3 rows) + exp                          ~ 80 px
    --   sep + Stats label + 7 stats + HP/MP/Atk/Def             ~190 px
    --   sep + Equipment label + 16 slot rows                    ~340 px
    -- Plus window chrome (title bar + char selector + Reload row +
    -- tab strip + padding) ~130 px = ~740 px content + chrome → 840 px
    -- gives a margin so font-size variance doesn't push the bottom
    -- equipment rows under the resize handle. History tab's width
    -- floor (Dummy(620, 0)) still pins horizontal consistency. User
    -- can drag to resize.
    imgui.SetNextWindowSize(640, 840, ImGuiSetCond_FirstUseEver);
    autoutil.push_solid_window_bg();
    if not imgui.Begin('AutoMog', ui_open) then
        imgui.End();
        autoutil.pop_solid_window_bg();
        return;
    end

    -- Char selector dropdown (task #109). Far-left of the tab row. Drives the
    -- state.selected_char used by all read-paths (Inventory tab bag display,
    -- Transfer tab side caps, etc.). Source: sessioned PCs returned by
    -- 0x186 ALLIANCE_PC_LIST (the server's alliance walk inherently excludes
    -- offline / unsessioned chars). Action paths still target primary until
    -- tasks #110–#113 land — a banner below the tab row makes that explicit.
    do
        local party        = AshitaCore:GetDataManager():GetParty();
        local primary_name = (party and party:GetMemberName(0)) or '';
        if not state.char_selector_bootstrapped then
            autoutil.send_list_alliance_pcs();
            state.char_selector_bootstrapped = true;
        end
        if state.selected_char == nil and primary_name ~= '' then
            state.selected_char = primary_name;
            inv_cache_lib.ensure_inventory(state.selected_char);
            autoutil.send_get_job_info(primary_name);
        end

        local label = (state.selected_char ~= nil and state.selected_char ~= '') and state.selected_char or 'Pick char';
        if imgui.Button(label .. '##automog_char_pick', 160, 0) then
            autoutil.send_list_alliance_pcs();
            imgui.OpenPopup('##automog_char_pick_popup');
        end
        if imgui.BeginPopup('##automog_char_pick_popup') then
            local function pick(name)
                if name ~= state.selected_char then
                    state.selected_char = name;
                    -- Lazy: only fetch if we don't already have a cached
                    -- inventory for this char. Swapping between previously
                    -- viewed chars is now instant. Use the Reload Inventory
                    -- button (or any path that calls send_inv_request) for
                    -- an explicit refresh.
                    inv_cache_lib.ensure_inventory(name);
                    -- Fire a job-info fetch for the picked char so the
                    -- "Change Job" section in the Inventory tab has fresh
                    -- unlocked-mask + per-job levels to cycle through.
                    autoutil.send_get_job_info(name);
                    -- Profile for the Status tab. ensure() is debounced
                    -- so this is a no-op when the cache is already warm.
                    char_profile_cache.ensure(name);
                end
                imgui.CloseCurrentPopup();
            end
            if primary_name ~= '' and imgui.Selectable(primary_name .. ' (you)') then pick(primary_name) end
            imgui.Separator();
            local roster = autoutil.alliance_pcs or {};
            local listed = 0;
            for _, m in ipairs(roster) do
                if m.name ~= primary_name then
                    if imgui.Selectable(m.name) then pick(m.name); end
                    listed = listed + 1;
                end
            end
            if listed == 0 then imgui.TextDisabled('(no other sessioned chars)') end
            imgui.EndPopup();
        end
        -- Reload refreshes everything the window shows for the selected char:
        -- inventory, the Status-tab profile (stats / equipment / exp / etc. via
        -- char_profile_cache), and job info. Uses .request() (forced) so a warm
        -- cache is bypassed. Anchored to the right edge of the char-picker row.
        local reload_btn_w = C.calc_text_w('Reload') + 8;
        imgui.SameLine(imgui.GetWindowWidth() - reload_btn_w - 8);
        if imgui.Button('Reload##tabs') then
            C.send_inv_request();
            char_profile_cache.request(state.selected_char);
            autoutil.send_get_job_info(state.selected_char);
        end
    end

    for i, tab in ipairs(TABS) do
        if i > 1 then imgui.SameLine(); end
        local is_active = (tab == active_tab);
        if is_active then imgui.PushStyleColor(ImGuiCol_Button, 0.26, 0.59, 0.98, 1.0); end
        if imgui.Button(tab) then
            active_tab = tab;
        end
        if is_active then imgui.PopStyleColor(); end
    end
    imgui.Separator();

    -- Header line: which char is being displayed. Actions (Transfer / AH /
    -- Craft / Drop) now route cross-char to this same selected char server-side
    -- -- 0x194 transfer, 0x19A synth, and /ah/* each resolve the target by name
    -- behind an ownership check -- so the old "actions route to primary" caveat
    -- is gone. Shown for primary too so the header height matches across chars.
    do
        local party        = AshitaCore:GetDataManager():GetParty();
        local primary_name = (party and party:GetMemberName(0)) or '';
        local shown        = (state.selected_char ~= nil and state.selected_char ~= '') and state.selected_char or primary_name;
        if shown ~= '' then
            imgui.TextDisabled(string.format('[Display: %s]', shown));
        end
    end

    imgui.Dummy(0, 3);
    if inv_cache_lib.is_loading(state.selected_char) then
        local dots = string.rep('.', math.floor(autoutil.get_ms_since_epoch() / 1000) % 4);
        imgui.Text('Loading Inventory' .. dots);
    else
        local status_str = state.latest_status and string.format('[%s] %s', state.latest_status.source, state.latest_status.text) or '';
        imgui.TextDisabled(status_str);
    end
    imgui.Dummy(0, 3);
    imgui.Separator();

    local draw_fn = TAB_DRAW[active_tab];
    if draw_fn then draw_fn(); end

    imgui.End();
    autoutil.pop_solid_window_bg();
end);
