--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines

  autosell: sell items to the Auction House via the map's HTTP AH backend
  (POST /ah/sell → op_registry → post_tick applier). Retail 0x04E AUC path
  fully retired; no more AskCommit/LotIn two-step, no more 0x198 proxy
  wrap. See src/map/singleplayer/auction_http.cpp for the server side.
]]--

local autoutil        = require('autoutil');
local http_client     = require('http_client');
local loading_overlay = require('loading_overlay');

local mod = {};

local _src     = ((debug.getinfo(1, 'S').source or ''):match('^@(.+)$') or ''):gsub('[\\/][\\/]+', '\\');
local _dir     = _src:match('^(.*[/\\])[^/\\]+$') or '';
local CSV_PATH = (_dir:match('^(.*[/\\])[Aa]ddons[/\\]') or '') .. 'config\\autoitem\\items.csv';

-- Loading overlay key. The AH tab renders this overlay in place of its
-- normal content while a sell op is in flight.
local LOADING_KEY = 'automog:ah';

local state = {
    active         = false,
    pending        = 0,  -- ops still to complete in the current run
    total          = 0,  -- total ops queued in the current run
    status         = 'Idle',
    cancelled      = false,
};

mod.state = state;

-- task #115: cross-char target set by AutoMog. Sell dispatches to this
-- char's inventory when non-empty; falls back to primary otherwise.
mod.target_name = nil;

local prices = {};

local function load_prices()
    local f = io.open(CSV_PATH, 'r');
    if not f then
        autoutil.log('AutoSell', string.format('WARNING: could not open price CSV: %s', CSV_PATH));
        return;
    end
    local count = 0;
    local first = true;
    for line in f:lines() do
        if first then
            first = false;
        else
            local fields = {};
            for field in line:gmatch('([^,]+)') do
                table.insert(fields, field:match('^%s*(.-)%s*$'));
            end
            local id          = tonumber(fields[1]);
            local sell_single = fields[3] == '1';
            local sell_stacks = fields[7] == '1';
            if id then
                prices[id] = {
                    price_single = tonumber(fields[5]) or 0,
                    price_stacks = tonumber(fields[9]) or 0,
                    sell_single  = sell_single,
                    sell_stacks  = sell_stacks,
                };
                count = count + 1;
            end
        end
    end
    f:close();
    autoutil.log('AutoSell', string.format('Loaded %d price entries from CSV.', count));
end

function mod.on_load()
    load_prices();
end

-- Resolve the target char name for this send. Empty mod.target_name means
-- "sell as primary" — read the party manager slot 0. If both are empty
-- something is wrong (not logged in yet); the caller should have gated.
local function resolve_target_name()
    if mod.target_name ~= nil and mod.target_name ~= '' then
        return mod.target_name;
    end
    local party = AshitaCore:GetDataManager():GetParty();
    return (party and party:GetMemberName(0)) or '';
end

-- Fire one HTTP sell op. On completion, decrement pending and either
-- start the next queued item or finish the run.
local function fire_one(item, all_items, index)
    local primary_name = (AshitaCore:GetDataManager():GetParty() and
                          AshitaCore:GetDataManager():GetParty():GetMemberName(0)) or '';
    local body = {
        by      = primary_name,
        ['for'] = item.target_name,
        slot    = item.slot,
        itemId  = item.item_id,
        isStack = item.is_stack,
        price   = item.price,
    };
    state.status = string.format('Listing %d/%d: %s (%s)',
        index, state.total, item.name, item.is_stack and 'stack' or 'single');
    loading_overlay.begin(LOADING_KEY, state.status);
    http_client.await_op('/ah/sell', body, nil, function(result, err)
        if state.cancelled then
            -- Explicit stop request; drop remaining queue and unlock.
            state.pending = 0;
            state.active  = false;
            state.status  = 'Stopped.';
            loading_overlay.done(LOADING_KEY);
            return;
        end
        if err then
            autoutil.log('AutoSell', string.format('Failed to list %s: %s', item.name, err));
        else
            autoutil.log('AutoSell', string.format('Listed: %s (%s) @ %d gil',
                item.name, item.is_stack and 'stack' or 'single', item.price));
        end
        state.pending = state.pending - 1;
        if index < #all_items then
            fire_one(all_items[index + 1], all_items, index + 1);
        else
            state.active = false;
            state.status = string.format('Done: %d listing(s).', state.total);
            loading_overlay.done(LOADING_KEY);
        end
    end);
end

-- slots = { {index=n, item_id=n, count=n, name=str, stack_size=n}, ... } resolved from inv_cache by caller
function mod.queue_sells(slots, is_stack, quantity)
    if state.active then
        autoutil.log('AutoSell', 'Sell already in progress.'); return;
    end
    if not slots or #slots == 0 then return; end
    local item_id   = slots[1].item_id;
    local item_name = slots[1].name;
    local entry     = prices[item_id];
    if not entry then
        autoutil.log('AutoSell', string.format('No price entry in CSV for: %s', item_name)); return;
    end
    local price = is_stack and entry.price_stacks or entry.price_single;
    if not price or price < 1 then
        autoutil.log('AutoSell', string.format('Price is 0 or missing for %s (%s).',
            item_name, is_stack and 'stack' or 'single')); return;
    end
    local target_name = resolve_target_name();
    if target_name == '' then
        autoutil.log('AutoSell', 'No target char (not logged in?)'); return;
    end

    -- Build the flat item list first so we know total count before firing.
    -- Each entry maps 1:1 to one HTTP sell op.
    local items  = {};
    local queued = 0;
    for _, slot in ipairs(slots) do
        if queued >= quantity then break; end
        if is_stack then
            if slot.count < slot.stack_size then
                autoutil.log('AutoSell', string.format('Skipping slot %d: only %d/%d (not a full stack).',
                    slot.index, slot.count, slot.stack_size));
            else
                table.insert(items, { name = slot.name, slot = slot.index, item_id = slot.item_id,
                                       is_stack = true, price = price, target_name = target_name });
                queued = queued + 1;
            end
        else
            local from_this_slot = math.min(slot.count, quantity - queued);
            for _ = 1, from_this_slot do
                table.insert(items, { name = slot.name, slot = slot.index, item_id = slot.item_id,
                                       is_stack = false, price = price, target_name = target_name });
            end
            queued = queued + from_this_slot;
        end
    end
    if queued == 0 then
        autoutil.log('AutoSell', string.format('Nothing to queue for "%s" as %s.',
            item_name, is_stack and 'stack' or 'single')); return;
    end

    state.active    = true;
    state.cancelled = false;
    state.total     = queued;
    state.pending   = queued;
    state.status    = string.format('Queued %d listing(s) of %s (%s)',
        queued, item_name, is_stack and 'stack' or 'single');
    autoutil.log('AutoSell', string.format('Queuing %d listing(s) of "%s" as %s @ %d gil.',
        queued, item_name, is_stack and 'stack' or 'single', price));

    -- Kick off the first op; each completion chains the next in fire_one.
    fire_one(items[1], items, 1);
end

-- Retained for API compatibility. The old retail-packet response handler
-- listened for 0x04C and 0x199 to drive its state machine — both paths are
-- gone. Left as a no-op so on_incoming_packet callers can still route here
-- without erroring, and to reserve a hook for future needs.
function mod.on_incoming_packet(_id, _size, _data)
    return false;
end

-- Retained for compatibility with the automog render loop. The HTTP
-- pipeline is driven by http_client.tick() (which the addon already calls
-- once per frame from its render event), so nothing needs to run here.
function mod.on_render()
end

function mod.on_command(args)
    if not autoutil.unlocked then
        autoutil.log('AutoSell', 'Not unlocked.'); return true;
    end
    if args[1] == 'stop' then
        if state.active then
            state.cancelled = true;
            autoutil.log('AutoSell', 'Stop requested — will halt after current op.');
        else
            autoutil.log('AutoSell', 'Nothing to stop.');
        end
        return true;
    end
    autoutil.log('AutoSell', 'Usage: /automog sell <item name> single|stack <quantity>');
    return true;
end

return mod;
