--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local JSON     = require('json');
local autoutil = require('autoutil');

local mod = {};

local _src        = ((debug.getinfo(1, 'S').source or ''):match('^@(.+)$') or ''):gsub('[\\/][\\/]+', '\\');
local ADDON_DIR   = _src:match('^(.*[/\\])[^/\\]+$') or '';
local ASHITA_ROOT = ADDON_DIR:match('^(.*[/\\])[Aa]ddons[/\\]') or '';
local RECIPES_FILE = ASHITA_ROOT .. 'config\\autoitem\\recipes.lua';
local ALIASES_FILE = ASHITA_ROOT .. 'config\\autoitem\\aliases.json';

local COMBINE_ANS_OPC   = 0x006F;
-- 0x19A AUTOMOG_SYNTH now handles both the primary and non-primary cases
-- (#233 consolidation, 2026-06-17). When no explicit target is set, we pass
-- primary's name as TargetCharName. Server-side 0x19A is self-contained:
-- it parses the inner 0x161-shape body and calls synthutils::doInstantSynth
-- against the target's inventory. The retired packet is: 0x161 FAST_SYNTH
-- (synth logic moved into 0x19A).
local AUTOMOG_SYNTH_OPCODE = 0x019A;
local AUTOMOG_SYNTH_RESULT = 0x019B;
-- PKT_FMT remains the 0x161-shape inner body (HH header + B B HashNo/pad +
-- H Crystal + B B CrystalIdx/Items + 8×H ItemNo + 8×B TableNo + B B padding).
-- We still build this 32-byte inner buffer with FAST_SYNTH_OPCODE in the
-- header slot so the server's InnerSynth reinterpretation matches the legacy
-- 0x161 layout — the opcode header byte itself is informational since the
-- engine dispatch already routed to 0x19A's handler.
local FAST_SYNTH_HEADER_TAG = 0x0161;
local PKT_FMT           = 'HHBBHBBHHHHHHHHBBBBBBBBBB';
local SYNTH_COOLDOWN_MS = 200;
local TIMEOUT_MS        = 5000;
local BIT_RESULT        = 32;
local BIT_ITEM_LO       = 64;
local BIT_ITEM_HI       = 72;
local BIT_BREAK_BASE    = 80;

local RESULT_NAMES = {
    [0x00]='success', [0x01]='failed (crystal lost)', [0x02]='interrupted',
    [0x03]='canceled: bad recipe', [0x04]='canceled', [0x06]='canceled: skill too low',
    [0x07]='canceled: rare item', [0x0C]='success (desynth)', [0x0D]='must wait longer',
    [0x0E]='interrupted: critical',
};
local ABORT_RESULTS = { [0x03]=true, [0x06]=true, [0x07]=true };

local state = {
    active       = false,
    recipe_key   = nil,
    variant_idx  = 1,
    recipe       = nil,
    synths_done  = 0,
    synths_limit = nil,
    hq_limit     = nil,
    hq_done      = 0,
    hq_ids       = {},
    waiting      = false,
    sent_t       = 0,
    status       = 'Idle',
};
mod.state = state;

local recipes_by_key = {};
local aliases        = {};

local function load_recipes()
    local ok, result = pcall(dofile, RECIPES_FILE);
    if not ok or type(result) ~= 'table' then
        autoutil.log('AutoCraft', 'WARNING: could not load recipes.lua: ' .. tostring(result));
        return;
    end
    recipes_by_key = result;
    local count = 0;
    for _ in pairs(recipes_by_key) do count = count + 1; end
    autoutil.log('AutoCraft', string.format('Loaded %d recipe keys.', count));
end

local function load_aliases()
    local f = io.open(ALIASES_FILE, 'r');
    if not f then return; end
    local raw = f:read('*a');
    f:close();
    local ok, data = pcall(function() return JSON:decode(raw); end);
    if ok and type(data) == 'table' then
        aliases = data;
    end
end

local function save_aliases()
    local f = io.open(ALIASES_FILE, 'w');
    if not f then autoutil.log('AutoCraft', 'ERROR: could not write aliases.json'); return; end
    local ok, encoded = pcall(function() return JSON:encode_pretty(aliases); end);
    if ok then
        f:write(encoded);
    else
        local keys = {};
        for k in pairs(aliases) do table.insert(keys, k); end
        table.sort(keys);
        f:write('{\n');
        for i, k in ipairs(keys) do
            f:write(string.format('  "%s": "%s"%s\n', k, aliases[k], i < #keys and ',' or ''));
        end
        f:write('}\n');
    end
    f:close();
end

local function strip_variant_suffix(s)
    local base, v = s:match('^(.+)%s+v(%d+)$');
    if base then return base, tonumber(v); end
    return s, nil;
end

local function resolve_recipe(name)
    local key = name:lower();
    if recipes_by_key[key] then return key, recipes_by_key[key], nil; end
    local aliased = aliases[key];
    if aliased then
        local alias_key, alias_variant = strip_variant_suffix(aliased:lower());
        if recipes_by_key[alias_key] then return alias_key, recipes_by_key[alias_key], alias_variant; end
    end
    return nil, string.format('Unknown recipe: "%s"', name), nil;
end

mod.get_slots = nil;  -- injected by automog.lua; receives item_id, returns {{slot,count},...}

local function find_slots_by_id(item_id)
    if mod.get_slots then return mod.get_slots(item_id); end
    local results = {};
    local inv = AshitaCore:GetDataManager():GetInventory();
    for i = 1, inv:GetContainerMax(0) do
        local item = inv:GetItem(0, i);
        if item and item.Id == item_id and item.Count > 0 then
            table.insert(results, { slot = i, count = item.Count });
        end
    end
    return results;
end

local function item_name(item_id)
    local res = AshitaCore:GetResourceManager():GetItemById(item_id);
    if res and res.Name then
        local n = tostring(res.Name[0]):gsub('%z', '');
        if n ~= '' then return n; end
    end
    return 'id=' .. tostring(item_id);
end

local function allocate_ingredient(item_id, quantity)
    local slots = find_slots_by_id(item_id);
    local result = {};
    local remaining = quantity;
    for _, s in ipairs(slots) do
        local take = math.min(s.count, remaining);
        for _ = 1, take do table.insert(result, { id = item_id, slot = s.slot }); end
        remaining = remaining - take;
        if remaining == 0 then break; end
    end
    if remaining > 0 then
        return nil, string.format('Need %d "%s" but only have %d.', quantity, item_name(item_id), quantity - remaining);
    end
    return result, nil;
end

local function make_combine_ask(crystal_id, crystal_slot, item_ids, item_slots)
    local n = #item_ids;
    return struct.pack(PKT_FMT,
        FAST_SYNTH_HEADER_TAG, 0, 0, 0,
        crystal_id, crystal_slot, n,
        item_ids[1] or 0, item_ids[2] or 0, item_ids[3] or 0, item_ids[4] or 0,
        item_ids[5] or 0, item_ids[6] or 0, item_ids[7] or 0, item_ids[8] or 0,
        item_slots[1] or 0, item_slots[2] or 0, item_slots[3] or 0, item_slots[4] or 0,
        item_slots[5] or 0, item_slots[6] or 0, item_slots[7] or 0, item_slots[8] or 0,
        0, 0
    );
end

local function build_synth_packet(recipe)
    local crystal_slots = find_slots_by_id(recipe.crystal);
    if #crystal_slots == 0 then
        return nil, string.format('Out of crystals: "%s".', item_name(recipe.crystal));
    end
    local needed = {};
    local order  = {};
    for _, id in ipairs(recipe.ingredients) do
        if not needed[id] then needed[id] = 0; table.insert(order, id); end
        needed[id] = needed[id] + 1;
    end
    local pairs_list = {};
    for _, id in ipairs(order) do
        local alloc, err = allocate_ingredient(id, needed[id]);
        if not alloc then return nil, err; end
        for _, e in ipairs(alloc) do table.insert(pairs_list, e); end
    end
    if #pairs_list < 1 then return nil, 'Recipe has no ingredients.'; end
    if #pairs_list > 8 then return nil, string.format('Recipe needs %d ingredient slots (max 8).', #pairs_list); end
    table.sort(pairs_list, function(a, b) return a.id < b.id; end);
    local item_ids = {}; local item_slots = {};
    for _, p in ipairs(pairs_list) do
        table.insert(item_ids,   p.id);
        table.insert(item_slots, p.slot);
    end
    return make_combine_ask(recipe.crystal, crystal_slots[1].slot, item_ids, item_slots), nil;
end

local function stop_crafting(reason)
    state.active  = false;
    state.waiting = false;
    local msg = string.format('Stopped after %d synth(s). %s', state.synths_done, reason or '');
    autoutil.log('AutoCraft', msg);
    state.status = msg;
end

mod.recipe_list = {};  -- { key, variants } sorted by key

function mod.get_recipe(key)
    return recipes_by_key[key and key:lower() or ''];
end

local function rebuild_list()
    mod.recipe_list = {};
    -- One entry PER RECIPE VARIANT (key + vidx), not per item name — items with
    -- several recipes (Prism Powder, Silent Oil, ...) each get their own row.
    -- `variants` still carries the total count so callers can tell singles apart.
    for key, variants in pairs(recipes_by_key) do
        local n = #variants;
        for i = 1, n do
            table.insert(mod.recipe_list, { key = key, vidx = i, variants = n });
        end
    end
    table.sort(mod.recipe_list, function(a, b)
        if a.key ~= b.key then return a.key < b.key; end
        return a.vidx < b.vidx;
    end);
end

function mod.on_load()
    load_recipes();
    load_aliases();
    rebuild_list();
end

function mod.on_incoming_packet(id, size, data)
    -- task #116: 0x19B AUTOMOG_SYNTH_RESULT carries wrapper-level error codes
    -- (no target, ownership rejected, inner mismatch). The real synth result
    -- still comes via COMBINE_ANS — mirrored to us by the server when the
    -- target's resolution finishes — so on a successful proxied synth we'll
    -- see status=0 here AND a COMBINE_ANS later.
    if id == AUTOMOG_SYNTH_RESULT then
        local status = struct.unpack('B', data, 5);
        if status ~= 0 and state.waiting then
            state.waiting = false;
            local msg = (status == 1) and 'target not sessioned'
                     or (status == 2) and 'ownership rejected'
                     or 'proxied synth failed';
            autoutil.log('AutoCraft', 'Proxy: ' .. msg);
            state.status = 'Proxy: ' .. msg;
            stop_crafting(msg);
        end
        return false;
    end
    if id ~= COMBINE_ANS_OPC then return false; end
    if not autoutil.unlocked or not state.waiting then return false; end
    local result = ashita.bits.unpack_be(data, BIT_RESULT, 8);
    state.waiting = false;
    state.synths_done = state.synths_done + 1;

    local label;
    if result == 0x00 or result == 0x0C then
        local lo = ashita.bits.unpack_be(data, BIT_ITEM_LO, 8);
        local hi = ashita.bits.unpack_be(data, BIT_ITEM_HI, 8);
        local item_no = lo + hi * 256;
        if state.hq_ids[item_no] then state.hq_done = state.hq_done + 1; end
        label = item_no ~= 0 and item_name(item_no) or state.recipe_key;
    else
        local lost = {};
        for i = 0, 7 do
            local lo = ashita.bits.unpack_be(data, BIT_BREAK_BASE + i * 16,     8);
            local hi = ashita.bits.unpack_be(data, BIT_BREAK_BASE + i * 16 + 8, 8);
            local id2 = lo + hi * 256;
            if id2 ~= 0 then table.insert(lost, item_name(id2)); end
        end
        label = #lost > 0 and ('Break [' .. table.concat(lost, ', ') .. ']') or 'Break';
    end

    local limit_str;
    if state.hq_limit then
        limit_str = string.format('%d synths, %d/%d HQ', state.synths_done, state.hq_done, state.hq_limit);
    elseif state.synths_limit then
        limit_str = string.format('%d/%d', state.synths_done, state.synths_limit);
    else
        limit_str = tostring(state.synths_done);
    end
    autoutil.log('AutoCraft', string.format('Result: %s (%s)', label, limit_str));
    state.status = string.format('%s — %s', label, limit_str);

    if ABORT_RESULTS[result] then
        stop_crafting('Unrecoverable result.');
    elseif state.hq_limit and state.hq_done >= state.hq_limit then
        stop_crafting('Reached requested HQ count.');
    elseif state.synths_limit and state.synths_done >= state.synths_limit then
        stop_crafting('Reached requested count.');
    end
    return false;
end

-- task #116: optional cross-char target. AutoMog sets this to selected_char
-- so synth dispatches against the target via the 0x19A wrapper.
mod.target_name = nil;

local function send_synth_packet(pkt_str)
    local party        = AshitaCore:GetDataManager():GetParty();
    local primary_name = (party and party:GetMemberName(0)) or '';
    local effective    = (mod.target_name ~= nil and mod.target_name ~= '')
                          and mod.target_name or primary_name;
    -- Always 0x19A AUTOMOG_SYNTH (#233 consolidation). When no target is set,
    -- we pass primary's own name so the server runs doInstantSynth against
    -- primary's inventory — same effect as the old 0x161 direct path.
    local fmt  = 'HH' .. string.rep('B', 16) .. string.rep('B', 64);
    local args = { AUTOMOG_SYNTH_OPCODE, 0 };
    local t    = effective:sub(1, 15);
    for i = 1, 16 do args[#args + 1] = (i <= #t) and string.byte(t, i) or 0; end
    for i = 1, 64 do args[#args + 1] = pkt_str:byte(i) or 0; end
    AddOutgoingPacket(AUTOMOG_SYNTH_OPCODE, struct.pack(fmt, unpack(args)):totable());
end

function mod.on_render()
    if not state.active or not autoutil.unlocked then return; end
    local ok, err = xpcall(function()
        local now = autoutil.get_ms_since_epoch();
        if state.waiting then
            if state.sent_t > 0 and now > state.sent_t + TIMEOUT_MS then
                autoutil.log('AutoCraft', 'Timed out waiting for COMBINE_ANS, continuing.');
                state.waiting = false;
            end
            return;
        end
        if state.sent_t > 0 and now < state.sent_t + SYNTH_COOLDOWN_MS then return; end
        local pkt, build_err = build_synth_packet(state.recipe);
        if not pkt then
            stop_crafting(build_err);
            return;
        end
        send_synth_packet(pkt);
        state.waiting = true;
        state.sent_t  = now;
    end, debug.traceback);
    if not ok then
        autoutil.log('AutoCraft', 'render error: ' .. tostring(err));
        stop_crafting('Internal error.');
    end
end

function mod.on_command(args)
    if not autoutil.unlocked then
        autoutil.log('AutoCraft', 'Not unlocked.'); return true;
    end

    if args[1] == 'stop' then
        if state.active then stop_crafting('Stopped by user.')
        else autoutil.log('AutoCraft', 'Nothing running.'); end
        return true;
    end

    if args[1] == 'search' then
        if not args[2] then autoutil.log('AutoCraft', 'Usage: /automog craft search <term>'); return true; end
        local term = table.concat(args, ' ', 2):lower();
        local count = 0;
        for key, variants in pairs(recipes_by_key) do
            if key:find(term, 1, true) then
                local var_str = #variants > 1 and string.format(' (%d variants)', #variants) or '';
                autoutil.log('AutoCraft', key .. var_str);
                count = count + 1;
            end
        end
        if count == 0 then autoutil.log('AutoCraft', string.format('No recipes matching "%s".', term))
        else autoutil.log('AutoCraft', string.format('%d result(s).', count)); end
        return true;
    end

    if args[1] == 'info' then
        if not args[2] then autoutil.log('AutoCraft', 'Usage: /automog craft info <name>'); return true; end
        local name = table.concat(args, ' ', 2);
        local key, variants, _ = resolve_recipe(name);
        if not variants then autoutil.log('AutoCraft', key); return true; end
        local res_mgr = AshitaCore:GetResourceManager();
        local function iname(id)
            if not id or id == 0 then return '?'; end
            local res = res_mgr:GetItemById(id);
            if res and res.Name then local n = tostring(res.Name[0]):gsub('%z',''); if n ~= '' then return n; end end
            return 'id='..tostring(id);
        end
        autoutil.log('AutoCraft', string.format('%s (%d variant(s)):', key, #variants));
        for i, v in ipairs(variants) do
            local ing_counts = {}; local ing_order = {};
            for _, id in ipairs(v.ingredients) do
                if not ing_counts[id] then ing_counts[id] = 0; table.insert(ing_order, id); end
                ing_counts[id] = ing_counts[id] + 1;
            end
            local ing_parts = {};
            for _, id in ipairs(ing_order) do table.insert(ing_parts, string.format('%s (x%d)', iname(id), ing_counts[id])); end
            autoutil.log('AutoCraft', string.format('  v%d Crystal:%s NQ:%s (x%d) Ings:%s', i, iname(v.crystal), iname(v.result), v.qty, table.concat(ing_parts, ', ')));
        end
        return true;
    end

    if args[1] == 'alias' then
        if args[2] == 'list' then
            local keys = {};
            for k in pairs(aliases) do table.insert(keys, k); end
            table.sort(keys);
            if #keys == 0 then autoutil.log('AutoCraft', 'No aliases defined.')
            else for _, k in ipairs(keys) do autoutil.log('AutoCraft', string.format('  %s -> %s', k, aliases[k])); end end
            return true;
        end
        if args[2] == 'add' then
            if not args[3] or not args[4] then autoutil.log('AutoCraft', 'Usage: /automog craft alias add <alias> <recipe> [v<n>]'); return true; end
            local alias = args[3]:lower();
            local value = table.concat(args, ' ', 4):lower();
            local base, var = strip_variant_suffix(value);
            if not recipes_by_key[base] then autoutil.log('AutoCraft', string.format('Unknown recipe: "%s"', base)); return true; end
            aliases[alias] = value;
            save_aliases();
            autoutil.log('AutoCraft', string.format('Alias added: %s -> %s', alias, value));
            return true;
        end
        if args[2] == 'remove' then
            if not args[3] then autoutil.log('AutoCraft', 'Usage: /automog craft alias remove <alias>'); return true; end
            local alias = table.concat(args, ' ', 3):lower();
            if aliases[alias] then aliases[alias] = nil; save_aliases(); autoutil.log('AutoCraft', string.format('Alias removed: %s', alias))
            else autoutil.log('AutoCraft', string.format('No alias: %s', alias)); end
            return true;
        end
        autoutil.log('AutoCraft', 'Usage: /automog craft alias add|remove|list');
        return true;
    end

    local usage = 'Usage: /automog craft recipe <name> [v<n>] [<count>|all|hq<N>]';
    if args[1] ~= 'recipe' then autoutil.log('AutoCraft', usage); return true; end
    if not args[2] then autoutil.log('AutoCraft', usage); return true; end

    local name_end = #args;
    local synths_limit = nil; local hq_limit = nil; local explicit_variant = nil;
    local last = args[name_end]:lower();
    if last == 'all' then
        name_end = name_end - 1;
    else
        local hq_n = last:match('^hq(%d+)$');
        if hq_n then
            hq_limit = tonumber(hq_n);
            if hq_limit < 1 then autoutil.log('AutoCraft', 'HQ count must be >= 1.'); return true; end
            name_end = name_end - 1;
        else
            local n = tonumber(last);
            if n and not last:match('^v%d+$') then
                if n < 1 then autoutil.log('AutoCraft', 'Synth count must be >= 1.'); return true; end
                synths_limit = math.floor(n);
                name_end = name_end - 1;
            end
        end
    end
    if name_end >= 2 then
        local v = args[name_end]:lower():match('^v(%d+)$');
        if v then explicit_variant = tonumber(v); name_end = name_end - 1; end
    end
    if name_end < 2 then autoutil.log('AutoCraft', usage); return true; end

    local recipe_name = table.concat(args, ' ', 2, name_end);
    local key, variants, alias_variant = resolve_recipe(recipe_name);
    if not key then autoutil.log('AutoCraft', variants); return true; end

    local variant_idx = explicit_variant or alias_variant or 1;
    if variant_idx < 1 or variant_idx > #variants then
        autoutil.log('AutoCraft', string.format('"%s" has %d variant(s). Use v1..v%d.', key, #variants, #variants));
        return true;
    end

    local recipe = variants[variant_idx];
    local hq_ids = {};
    if hq_limit then
        for _, hq_id in ipairs(recipe.hq or {}) do
            if hq_id ~= recipe.result then hq_ids[hq_id] = true; end
        end
        if not next(hq_ids) then
            autoutil.log('AutoCraft', string.format('"%s" has no distinct HQ result.', key));
            return true;
        end
    end

    state.active       = true;
    state.recipe_key   = key;
    state.variant_idx  = variant_idx;
    state.recipe       = recipe;
    state.synths_done  = 0;
    state.synths_limit = synths_limit;
    state.hq_limit     = hq_limit;
    state.hq_done      = 0;
    state.hq_ids       = hq_ids;
    state.waiting      = false;
    state.sent_t       = 0;
    local limit_label = synths_limit and ('x'..synths_limit) or hq_limit and ('hq'..hq_limit) or 'all';
    state.status = string.format('Running: %s v%d [%s]', key, variant_idx, limit_label);
    autoutil.log('AutoCraft', state.status);
    return true;
end

return mod;
