--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local autoutil = require('autoutil');

local mod = {};

-- 0x196 AUTOMOG_BOX_PULL handles both the primary and non-primary cases now —
-- when no explicit target is given (primary's own box), we just pass primary's
-- name as the target. Server-side 0x196 looks up the char by name and runs the
-- pull against their delivery box → their inventory. The old 0x164 AUTOBOX
-- primary-direct path was deprecated 2026-06-17 (#233 consolidation).
local AUTOMOG_BOX_PULL_OPCODE = 0x196;
local AUTOMOG_BOX_RESULT      = 0x197;

mod.state = {
    active = false,
    done   = 0,
    status = 'Idle',
};

local function make_automog_packet(target_name)
    local fmt  = 'HH' .. string.rep('B', 16);
    local args = { AUTOMOG_BOX_PULL_OPCODE, 0 };
    local s    = (target_name or ''):sub(1, 15);
    for i = 1, 16 do
        args[#args + 1] = (i <= #s) and string.byte(s, i) or 0;
    end
    return struct.pack(fmt, unpack(args));
end

-- target_name: optional. If nil/empty/local-primary, we pull primary's own box
-- by passing primary's name through 0x196. Otherwise pull the named target's
-- box (must be a headless owned by the same primary). Always replies via
-- a single 0x197 summary packet.
function mod.retrieve(target_name)
    if not autoutil.unlocked then
        autoutil.log('AutoBox', 'Not unlocked.');
        return;
    end
    if mod.state.active then
        autoutil.log('AutoBox', 'Already running.');
        return;
    end

    local party        = AshitaCore:GetDataManager():GetParty();
    local primary_name = (party and party:GetMemberName(0)) or '';
    local effective    = (target_name ~= nil and target_name ~= '')
                          and target_name or primary_name;

    mod.state.active      = true;
    mod.state.done        = 0;
    mod.state.status      = 'Retrieving...';
    mod.state.target_name = effective;

    autoutil.log('AutoBox', string.format('Retrieving delivery box for %s...', effective));
    AddOutgoingPacket(AUTOMOG_BOX_PULL_OPCODE, make_automog_packet(effective):totable());
end

function mod.on_incoming_packet(id, size, data)
    if id == AUTOMOG_BOX_RESULT and mod.state.active then
        local result = struct.unpack('B', data, 5);
        local moved  = struct.unpack('B', data, 6);
        mod.state.done   = moved;
        mod.state.active = false;
        if result == 1 then
            mod.state.status = string.format('Inv full (%d retrieved)', moved);
            autoutil.log('AutoBox', string.format('Inventory full - retrieved %d item(s).', moved));
        elseif result == 0 then
            mod.state.status = string.format('Done (%d retrieved)', moved);
            autoutil.log('AutoBox', string.format('Done. Retrieved %d item(s).', moved));
        else
            mod.state.status = 'Failed';
            autoutil.log('AutoBox', 'Box pull failed (target offline / not owned).');
        end
        -- Refresh inv cache for the target char so AutoMog's Inventory tab
        -- reflects the items that just moved into their bag.
        if mod.state.target_name and moved > 0 then
            local inv_cache = require('inv_cache');
            inv_cache.send_inv_request(mod.state.target_name);
        end
        mod.state.target_name = nil;
        return false;
    end
    return false;
end

function mod.on_command(cmd)
    local args = cmd:args();
    if #args == 0 or args[1]:lower() ~= '/autobox' then return false; end
    mod.retrieve();
    return true;
end

return mod;
