--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local JSON            = require('json');
local spells          = require('spells');
local scrolls         = require('scrolls');
local autoutil        = require('autoutil');
local http_client     = require('http_client');
local loading_overlay = require('loading_overlay');

-- Loading overlay key shared with autosell.lua so the AH tab's single
-- overlay covers both sell and buy runs. Only one AH run at a time is
-- supported anyway.
local LOADING_KEY = 'automog:ah';

local mod = {};

local _src        = ((debug.getinfo(1, 'S').source or ''):match('^@(.+)$') or ''):gsub('[\\/][\\/]+', '\\');
local ADDON_DIR   = _src:match('^(.*[/\\])[^/\\]+$') or '';
local ASHITA_ROOT = ADDON_DIR:match('^(.*[/\\])[Aa]ddons[/\\]') or '';
local CSV_PATH     = ASHITA_ROOT .. 'config\\autoitem\\items.csv';
local RECIPES_FILE = ASHITA_ROOT .. 'config\\autoitem\\recipes.lua';
local ALIASES_FILE = ASHITA_ROOT .. 'config\\autoitem\\aliases.json';
local GROUPS_DIR   = ASHITA_ROOT .. 'config\\autoitem\\groups\\';

-- Retail AH (0x04E AUC / 0x04C response) constants are gone: every AH
-- interaction now goes over loopback HTTP. Sell/buy/cancel POST to
-- /ah/{sell,buy,cancel}; listings and stock counts GET from
-- /ah/{listings,stock}. Only NPC vendor shops still speak packets.
local ACTION_OPCODE     = 0x001A;
local SHOP_BUY_OPCODE   = 0x0083;
local SHOP_OPEN_ID      = 0x003E;
local SHOP_LIST_ID      = 0x003C;
local SHOP_BUY_S2C_ID   = 0x003F;
local SHOP_FLAGS_LAST   = 0x89;
local VENDOR_TIMEOUT    = 4.0;
local SHOP_BIT_OFFSET   = 40;
local SHOP_BIT_FLAGS    = 56;
local SHOP_BIT_FIRST    = 72;
-- task #115: per-char AH. When mod.target_name is non-empty and != primary,
-- the AH acts on that headless instead. This used to ride the 0x198 AUTOMOG_AH
-- proxy packet; the HTTP endpoints take the target directly as the `for` field
-- on the request body, so the wrapper (and its 0x199 result packet) is gone.
-- NPC vendor shops stay primary-only and still speak packets: they require the
-- buying char to have an active shop event (standing at and talking to the
-- vendor), which no server-side dispatch can arrange.
mod.target_name = nil;

local state = {
    queue          = {},
    waiting        = false,
    active         = false,
    last_t         = 0,
    current_name   = nil,
    current_bought = 0,
    recipe_key     = nil,
    status         = 'Idle',
};
mod.state = state;

local vendor = { pending = nil, cache = nil, sent_at = nil };
-- In-flight guard for the async GET /ah/stock pre-check. The request's own
-- data (checks/purchases/recipe/...) lives in the callback closure; this state
-- exists only so a reply already in flight can be abandoned. `gen` bumps on
-- every start and on mod.stop(), so a stale reply that lands after a newer
-- check began (or after a stop) is dropped instead of racing the live one.
local ah_query = { waiting = false, gen = 0 };
local prices = {};
local recipes_by_key = {};
local aliases        = {};
local groups_by_key  = {};

local function load_prices()
    local f = io.open(CSV_PATH, 'r');
    if not f then autoutil.log('AutoBuy', string.format('WARNING: could not open price CSV: %s', CSV_PATH)); return; end
    local count = 0; local first = true;
    for line in f:lines() do
        if first then first = false;
        else
            local fields = {};
            for field in line:gmatch('([^,]+)') do table.insert(fields, field:match('^%s*(.-)%s*$')); end
            local id = tonumber(fields[1]);
            local sell_single = fields[3] == '1';
            local sell_stacks = fields[7] == '1';
            if id and (sell_single or sell_stacks) then
                prices[id] = {
                    price_single = tonumber(fields[5])  or 0,
                    stock_single = tonumber(fields[6])  or 0,
                    price_stacks = tonumber(fields[9])  or 0,
                    stock_stacks = tonumber(fields[10]) or 0,
                    sell_single  = sell_single,
                    sell_stacks  = sell_stacks,
                };
                count = count + 1;
            end
        end
    end
    f:close();
    autoutil.log('AutoBuy', string.format('Loaded %d price entries from CSV.', count));
end

local function load_recipes()
    local ok, result = pcall(dofile, RECIPES_FILE);
    if not ok or type(result) ~= 'table' then
        autoutil.log('AutoBuy', 'WARNING: could not load recipes.lua: ' .. tostring(result)); return;
    end
    recipes_by_key = result;
    local count = 0; for _ in pairs(recipes_by_key) do count = count + 1; end
    autoutil.log('AutoBuy', string.format('Loaded %d recipe keys.', count));
end

local function load_aliases()
    local f = io.open(ALIASES_FILE, 'r');
    if not f then return; end
    local raw = f:read('*a'); f:close();
    local ok, data = pcall(function() return JSON:decode(raw); end);
    if ok and type(data) == 'table' then aliases = data; end
end

local function load_groups()
    local handle = io.popen(string.format('dir /b "%s*.json" 2>nul', GROUPS_DIR));
    if not handle then return; end
    local count = 0;
    for filename in handle:lines() do
        local path = GROUPS_DIR .. filename;
        local f = io.open(path, 'r');
        if f then
            local raw = f:read('*a'); f:close();
            local ok, data = pcall(function() return JSON:decode(raw); end);
            if ok and type(data) == 'table' then
                local entry = { name = data.name, list = data.list or {} };
                local keys = { (data.name or ''):lower() };
                if type(data.aliases) == 'table' then
                    for _, alias in ipairs(data.aliases) do table.insert(keys, alias:lower()); end
                end
                for _, key in ipairs(keys) do groups_by_key[key] = entry; end
                count = count + 1;
            end
        end
    end
    handle:close();
    autoutil.log('AutoBuy', string.format('Loaded %d group file(s).', count));
end

local function get_price(item_id, is_stack)
    local entry = prices[item_id];
    if not entry then return nil, false; end
    if is_stack then return entry.price_stacks, entry.sell_stacks;
    else return entry.price_single, entry.sell_single; end
end

local function strip_variant_suffix(s)
    local base, v = s:match('^(.+)%s+v(%d+)$');
    if base then return base, tonumber(v); end
    return s, nil;
end

local function resolve_recipe(name)
    local key = name:lower();
    if recipes_by_key[key] then return key, recipes_by_key[key], nil; end
    local aliased = aliases[key];
    if aliased then
        local alias_key, alias_variant = strip_variant_suffix(aliased:lower());
        if recipes_by_key[alias_key] then return alias_key, recipes_by_key[alias_key], alias_variant; end
    end
    return nil, nil, nil;
end

local function resolve_purchases(item_id, items_needed, prefer_stack)
    local e = prices[item_id];
    if not e then return nil; end
    local stacks_avail  = e.sell_stacks and e.stock_stacks or 0;
    local singles_avail = e.sell_single and e.stock_single or 0;
    local function stack_group(n) return { is_stack=true,  count=n, price=e.price_stacks }; end
    local function single_group(n) return { is_stack=false, count=n, price=e.price_single }; end
    if prefer_stack then
        local stacks_needed = math.ceil(items_needed / 12);
        if stacks_avail >= stacks_needed then return { stack_group(stacks_needed) }; end
        local items_from_stacks = stacks_avail * 12;
        local singles_needed    = items_needed - items_from_stacks;
        if singles_avail < singles_needed then return nil; end
        local result = {};
        if stacks_avail > 0 then table.insert(result, stack_group(stacks_avail)); end
        table.insert(result, single_group(singles_needed));
        return result;
    else
        if items_needed >= 4 and stacks_avail > 0 then
            local stacks_needed = math.ceil(items_needed / 12);
            if stacks_avail >= stacks_needed then return { stack_group(stacks_needed) }; end
            local items_from_stacks = stacks_avail * 12;
            local singles_needed    = items_needed - items_from_stacks;
            if singles_avail >= singles_needed then
                local result = {};
                table.insert(result, stack_group(stacks_avail));
                if singles_needed > 0 then table.insert(result, single_group(singles_needed)); end
                return result;
            end
        end
        if singles_avail >= items_needed then return { single_group(items_needed) }; end
        local remaining = items_needed - singles_avail;
        local stacks_needed = math.ceil(remaining / 12);
        if stacks_avail >= stacks_needed then
            local result = {};
            if singles_avail > 0 then table.insert(result, single_group(singles_avail)); end
            table.insert(result, stack_group(stacks_needed));
            return result;
        end
        return nil;
    end
end

local function item_display_name(item_id)
    local res = AshitaCore:GetResourceManager():GetItemById(item_id);
    if res and res.Name then
        local n = tostring(res.Name[0]):gsub('%z', '');
        if n ~= '' then return n; end
    end
    return 'id=' .. tostring(item_id);
end

local function find_item_id_by_name(name)
    local res = AshitaCore:GetResourceManager():GetItemByName(name, 0);
    if res then return res.ItemId; end
    return nil;
end

local function find_available_recipe(variants, is_stack, quantity)
    for _, recipe in ipairs(variants) do
        local valid = true; local purchases = {};
        local yield = recipe.qty or 1;
        local synths = math.ceil(quantity / yield);
        local needed = {}; local order = {};
        for _, id in ipairs(recipe.ingredients) do
            if not needed[id] then needed[id] = 0; table.insert(order, id); end
            needed[id] = needed[id] + 1;
        end
        for _, item_id in ipairs(order) do
            local groups = resolve_purchases(item_id, needed[item_id] * synths, is_stack);
            if not groups then valid = false; break; end
            local name = item_display_name(item_id);
            for _, g in ipairs(groups) do
                table.insert(purchases, { name=name, item_id=item_id, is_stack=g.is_stack, count=g.count, price=g.price });
            end
        end
        if valid then return recipe, purchases, synths; end
    end
    return nil, nil, nil;
end

local function find_partial_recipe(recipe, is_stack, quantity)
    if not recipe then return nil, {}, 0; end
    local purchases = {};
    local yield = recipe.qty or 1;
    local synths = math.ceil(quantity / yield);
    local needed = {}; local order = {};
    for _, id in ipairs(recipe.ingredients) do
        if not needed[id] then needed[id] = 0; table.insert(order, id); end
        needed[id] = needed[id] + 1;
    end
    for _, item_id in ipairs(order) do
        local groups = resolve_purchases(item_id, needed[item_id] * synths, is_stack);
        if groups then
            local name = item_display_name(item_id);
            for _, g in ipairs(groups) do
                table.insert(purchases, { name=name, item_id=item_id, is_stack=g.is_stack, count=g.count, price=g.price });
            end
        end
    end
    return recipe, purchases, synths;
end

local function free_inventory_slots()
    local inv = AshitaCore:GetDataManager():GetInventory();
    local max = inv:GetContainerMax(0);
    local used = 0;
    for i = 0, max do
        local item = inv:GetItem(0, i);
        if item and item.Id ~= 0 then used = used + 1; end
    end
    return max - used;
end

-- AH bid entry factory. Bids fire via POST /ah/buy, so this is a plain
-- table -- see send_next below.
local function make_bid(item_id, is_stack, bid_price)
    return { item_id = item_id, is_stack = is_stack and true or false, bid_price = bid_price };
end

local function make_npc_talk(server_id, target_index)
    return struct.pack('HHLHHLLLL', ACTION_OPCODE, 0x08, server_id, target_index, 0x00, 0, 0, 0, 0);
end

local function make_shop_buy(shop_item_index, qty)
    return struct.pack('HHIHHBBBB', SHOP_BUY_OPCODE, 0, qty, 0, shop_item_index, 0, 0, 0, 0);
end

-- Ask the server how many active listings exist for each (item_id, is_stack)
-- group in `checks`. Read-only, so it goes straight to the map server's HTTP
-- thread. This replaces the retired 0x162 AH_QUERY packet, whose handler ran a
-- COUNT(*) per group on the map tick thread and tripped the inactivity
-- watchdog when the craft tab pre-checked a recipe's ingredients.
--
-- callback(avail, err): `avail` is index-aligned to `checks`, or nil on error.
local function request_ah_stock(checks, callback)
    local parts = {};
    for i, chk in ipairs(checks) do
        parts[i] = string.format('%d:%d', chk.item_id, chk.is_stack and 1 or 0);
    end
    local path = '/ah/stock?items=' .. table.concat(parts, ',');
    http_client.get(path, function(code, body, _, err)
        if err ~= nil or code ~= 200 then
            callback(nil, err or string.format('HTTP %s', tostring(code)));
            return;
        end
        local ok, arr = pcall(function() return JSON:decode(body); end);
        if not ok or type(arr) ~= 'table' or #arr ~= #checks then
            callback(nil, 'malformed /ah/stock response');
            return;
        end
        local avail = {};
        for i = 1, #checks do
            avail[i] = tonumber(arr[i].count) or 0;
        end
        callback(avail, nil);
    end);
end

local function parse_args(cmd)
    local result = {}; local i = 1;
    while i <= #cmd do
        local c = cmd:sub(i, i);
        if c == ' ' then i = i + 1;
        elseif c == '"' then
            local j = cmd:find('"', i + 1, true);
            if j then table.insert(result, cmd:sub(i + 1, j - 1)); i = j + 1;
            else table.insert(result, cmd:sub(i + 1)); break; end
        else
            local j = cmd:find(' ', i, true);
            if j then table.insert(result, cmd:sub(i, j - 1)); i = j + 1;
            else table.insert(result, cmd:sub(i)); break; end
        end
    end
    return result;
end

-- Drain one AH bid off state.queue via POST /ah/buy. On completion, either
-- start the next queued bid or unlock the overlay and mark done. Failures
-- log and skip the rest of that item's queue (matches retail behavior of
-- "if this SKU is gone, don't keep hammering for more of it").
local function send_next()
    local entry = table.remove(state.queue, 1);
    if entry.name ~= state.current_name then
        state.current_name   = entry.name;
        state.current_bought = 0;
    end
    state.active  = true;
    state.status  = string.format('Buying %s (%d left)', state.current_name or '...', #state.queue);
    loading_overlay.begin(LOADING_KEY, state.status);

    local party        = AshitaCore:GetDataManager():GetParty();
    local primary_name = (party and party:GetMemberName(0)) or '';
    local target_name  = (mod.target_name ~= nil and mod.target_name ~= '')
                          and mod.target_name or primary_name;
    local body = {
        by       = primary_name,
        ['for']  = target_name,
        itemId   = entry.bid.item_id,
        isStack  = entry.bid.is_stack,
        bidPrice = entry.bid.bid_price,
    };
    http_client.await_op('/ah/buy', body, nil, function(result, err)
        if err then
            local failed_name = state.current_name;
            local skipped     = 0;
            while #state.queue > 0 and state.queue[1].name == failed_name do
                table.remove(state.queue, 1); skipped = skipped + 1;
            end
            autoutil.log('AutoBuy', string.format('%s: purchased %d, failed %d (%s).',
                failed_name or 'item', state.current_bought, skipped + 1, err));
            state.current_name   = nil;
            state.current_bought = 0;
        else
            state.current_bought = state.current_bought + 1;
        end
        if #state.queue > 0 then
            send_next();
        else
            state.active       = false;
            state.status       = state.recipe_key and ('Done: ' .. state.recipe_key) or 'Done';
            state.current_name = nil;
            state.recipe_key   = nil;
            loading_overlay.done(LOADING_KEY);
        end
    end);
end

-- Turn a GET /ah/stock reply into a bid queue and start draining it.
--
-- `partial` false: every ingredient group must be fully in stock or the whole
-- run aborts. `partial` true: clamp each group down to what's actually listed
-- and buy whatever survives.
local function apply_ah_stock(avail, checks, purchases, key, partial)
    if not partial then
        for i, chk in ipairs(checks) do
            autoutil.log('AutoBuy', string.format('  AH stock: %s (%s) need %d have %d', chk.name, chk.is_stack and 'stack' or 'single', chk.count_needed, avail[i]));
            if avail[i] < chk.count_needed then
                autoutil.log('AutoBuy', string.format('Aborted: insufficient stock for %s.', chk.name));
                state.status = 'Aborted: insufficient stock';
                loading_overlay.done(LOADING_KEY);
                return;
            end
        end
    else
        local clamped = {};
        for i, chk in ipairs(checks) do
            local pkey = tostring(chk.item_id) .. ',' .. (chk.is_stack and '1' or '0');
            clamped[pkey] = math.min(chk.count_needed, avail[i]);
        end
        local filtered = {};
        for _, p in ipairs(purchases) do
            local pkey = tostring(p.item_id) .. ',' .. (p.is_stack and '1' or '0');
            local cnt = clamped[pkey];
            if cnt == nil then
                table.insert(filtered, p);
            elseif cnt > 0 then
                table.insert(filtered, { item_id=p.item_id, is_stack=p.is_stack, count=cnt, price=p.price, name=p.name });
            end
        end
        purchases = filtered;
        if #purchases == 0 then
            autoutil.log('AutoBuy', 'No available ingredients after AH stock check.');
            state.status = 'No available ingredients';
            loading_overlay.done(LOADING_KEY);
            return;
        end
    end

    state.queue          = {};
    state.waiting        = false;
    state.current_name   = nil;
    state.current_bought = 0;
    state.recipe_key     = key;
    for _, p in ipairs(purchases) do
        for _ = 1, p.count do
            table.insert(state.queue, { bid=make_bid(p.item_id, p.is_stack, p.price), name=p.name });
        end
    end
    autoutil.log('AutoBuy', string.format('Queued %d bid(s).', #state.queue));
    state.status = string.format('Queued %d bids for %s', #state.queue, key);
    send_next();
end

-- Fire the stock pre-check and hand the reply to apply_ah_stock. Guarded by
-- ah_query.waiting so mod.stop() can abandon an in-flight reply.
local function start_ah_stock_check(checks, purchases, key, partial)
    -- No groups to price means nothing to buy (recipe already covered by
    -- inventory). Bail before the request: /ah/stock rejects an empty ?items.
    if #checks == 0 then
        autoutil.log('AutoBuy', 'Nothing to buy -- ingredients already on hand.');
        state.status = 'Nothing to buy';
        return;
    end
    ah_query.waiting = true;
    ah_query.gen     = ah_query.gen + 1;
    local gen        = ah_query.gen;
    state.status     = 'Checking AH stock...';
    loading_overlay.begin(LOADING_KEY, state.status);
    autoutil.log('AutoBuy', string.format('Checking live AH stock for %d item group(s)...', #checks));
    request_ah_stock(checks, function(avail, err)
        if not ah_query.waiting or ah_query.gen ~= gen then
            return;
        end
        ah_query.waiting = false;
        if err ~= nil then
            autoutil.log('AutoBuy', string.format('AH stock check failed: %s', tostring(err)));
            state.status = 'AH stock check failed';
            loading_overlay.done(LOADING_KEY);
            return;
        end
        local ok, perr = xpcall(function()
            apply_ah_stock(avail, checks, purchases, key, partial);
        end, debug.traceback);
        if not ok then
            autoutil.log('AutoBuy', 'ah_stock error: ' .. tostring(perr));
            state.status = 'AH stock check failed';
            loading_overlay.done(LOADING_KEY);
        end
    end);
end

mod.recipe_list = {};  -- { key, variants } sorted by key
mod.group_list  = {};  -- display names sorted

local function rebuild_lists()
    mod.recipe_list = {};
    for key, variants in pairs(recipes_by_key) do
        table.insert(mod.recipe_list, { key = key, variants = #variants });
    end
    table.sort(mod.recipe_list, function(a, b) return a.key < b.key; end);

    local seen = {};
    mod.group_list = {};
    for _, entry in pairs(groups_by_key) do
        if not seen[entry.name] then
            seen[entry.name] = true;
            table.insert(mod.group_list, entry.name);
        end
    end
    table.sort(mod.group_list);
end

function mod.on_load()
    load_prices();
    load_recipes();
    load_aliases();
    load_groups();
    rebuild_lists();
end

function mod.on_incoming_packet(id, size, data)
    if not autoutil.unlocked then return false; end

    if id == SHOP_OPEN_ID then
        if vendor.pending then vendor.cache = {}; end
        return false;
    end

    if id == SHOP_LIST_ID then
        if not vendor.pending then return false; end
        if vendor.cache == nil then vendor.cache = {}; end
        local ok, err = xpcall(function()
            local offset = ashita.bits.unpack_be(data, SHOP_BIT_OFFSET, 16);
            local flags  = ashita.bits.unpack_be(data, SHOP_BIT_FLAGS,  8);
            for i = 0, 18 do
                local base    = SHOP_BIT_FIRST + i * 96;
                local price   = ashita.bits.unpack_be(data, base,      32);
                local item_id = ashita.bits.unpack_be(data, base + 32, 16);
                if item_id == 0 then break; end
                vendor.cache[offset + i] = { item_id=item_id, item_name=item_display_name(item_id), price=price };
            end
            if flags ~= SHOP_FLAGS_LAST then return; end
            local p = vendor.pending;
            local found_idx, found = nil, nil;
            for idx, entry in pairs(vendor.cache) do
                if entry.item_name:lower() == p.name_lc then found_idx = idx; found = entry; break; end
            end
            vendor.pending = nil;
            if not found then autoutil.log('AutoBuy', string.format('"%s" not found in vendor shop.', p.display)); return; end
            local total_items = p.is_stack and p.qty * 12 or p.qty;
            local remaining   = total_items;
            local transactions = math.ceil(total_items / 12);
            local free_slots = free_inventory_slots();
            if free_slots < transactions then
                autoutil.log('AutoBuy', string.format('Not enough inventory space (%d free, %d needed).', free_slots, transactions)); return;
            end
            autoutil.log('AutoBuy', string.format('Vendor: %s x%d @ %d gil each', found.item_name, total_items, found.price));
            state.status = string.format('Vendor: %s x%d', found.item_name, total_items);
            for _ = 1, transactions do
                local buy_qty = math.min(12, remaining);
                remaining = remaining - buy_qty;
                AddOutgoingPacket(SHOP_BUY_OPCODE, make_shop_buy(found_idx, buy_qty):totable());
            end
        end, debug.traceback);
        if not ok then autoutil.log('AutoBuy', 'vendor list error: ' .. tostring(err)); end
        return false;
    end

    if id == SHOP_BUY_S2C_ID then
        local ok, err = xpcall(function()
            local count = ashita.bits.unpack_be(data, 72, 32);
            autoutil.log('AutoBuy', string.format('Vendor purchase confirmed: %d item(s).', count));
            state.status = string.format('Vendor done (%d items)', count);
        end, debug.traceback);
        if not ok then autoutil.log('AutoBuy', 'vendor confirm error: ' .. tostring(err)); end
        return false;
    end

    -- Retail 0x04C AH response handler retired -- AH bid results now flow
    -- back through the HTTP /ah/buy op reply (see send_next above), and the
    -- stock pre-check through GET /ah/stock. Only the NPC vendor shop
    -- branches above still route through this incoming-packet path.
    return false;
end

function mod.on_render()
    if not autoutil.unlocked then return; end
    if vendor.pending and vendor.sent_at and os.clock() - vendor.sent_at >= VENDOR_TIMEOUT then
        autoutil.log('AutoBuy', 'Vendor timeout - no shop opened. Are you within range?');
        vendor.pending = nil; vendor.cache = nil; vendor.sent_at = nil;
        state.status = 'Vendor timeout';
    end
    -- AH bid queue advances via HTTP callbacks in send_next; nothing to
    -- retry-poke from render anymore.
end

function mod.buy_scrolls()
    if not autoutil.unlocked then autoutil.log('AutoBuy', 'Not unlocked.'); return; end
    local player    = AshitaCore:GetDataManager():GetPlayer();
    local mainJob   = player:GetMainJob();
    local mainJobLv = player:GetMainJobLevel();
    state.queue = {}; state.waiting = false; state.current_name = nil; state.current_bought = 0;
    local queued = 0;
    for _, spell in pairs(spells) do
        if not spell.unlearnable then
            local reqLevel = spell.levels[mainJob];
            if reqLevel ~= nil and mainJobLv >= reqLevel then
                if not player:HasSpell(spell.id) then
                    local scrollData = scrolls[spell.en];
                    if scrollData then
                        local bid_price, can_buy = get_price(scrollData.item_id, false);
                        if can_buy then
                            table.insert(state.queue, { bid=make_bid(scrollData.item_id, false, bid_price), name=spell.en });
                            queued = queued + 1;
                        end
                    end
                end
            end
        end
    end
    if queued == 0 then autoutil.log('AutoBuy', 'No scrolls to purchase.'); state.status = 'No scrolls to buy'; return; end
    autoutil.log('AutoBuy', string.format('Queued %d scroll bid(s).', queued));
    state.status = string.format('Buying %d scrolls', queued);
    send_next();
end

function mod.stop()
    local n = #state.queue;
    state.queue = {}; state.waiting = false; state.active = false; state.current_name = nil; state.current_bought = 0; state.recipe_key = nil;
    vendor.pending = nil; vendor.cache = nil; vendor.sent_at = nil;
    ah_query.waiting = false;
    ah_query.gen     = ah_query.gen + 1;
    state.status = 'Idle';
    loading_overlay.done(LOADING_KEY);
    autoutil.log('AutoBuy', string.format('Stopped. Cleared %d pending bid(s).', n));
end

-- Direct item buy by ID and known price (used by AH browse UI).
function mod.buy_item_direct(item_id, is_stack, qty, price)
    if not autoutil.unlocked then autoutil.log('AutoBuy', 'Not unlocked.'); return; end
    if not price or price <= 0 then autoutil.log('AutoBuy', 'Invalid price.'); return; end
    if not qty or qty < 1 then autoutil.log('AutoBuy', 'Invalid quantity.'); return; end
    state.queue = {}; state.waiting = false; state.current_name = nil; state.current_bought = 0;
    local name = item_display_name(item_id) or tostring(item_id);
    for _ = 1, qty do
        table.insert(state.queue, { bid=make_bid(item_id, is_stack, price), name=name });
    end
    state.active = true;
    state.status = string.format('Buying %s x%d', name, qty);
    autoutil.log('AutoBuy', string.format('Queued %d bid(s) for %s @ %d gil each.', #state.queue, name, price));
    send_next();
end

function mod.on_command(args)
    if not autoutil.unlocked then autoutil.log('AutoBuy', 'Not unlocked.'); return true; end

    local subcmd = args[1] and args[1]:lower();

    if subcmd == 'stop' then mod.stop(); return true; end

    if subcmd == 'scrolls' then mod.buy_scrolls(); return true; end

    if subcmd == 'item' then
        if #args < 4 then
            autoutil.log('AutoBuy', 'Usage: /automog buy item <item_id> single|stack <qty>'); return true;
        end
        local item_id  = tonumber(args[2]);
        local buy_type = args[3]:lower();
        local quantity = tonumber(args[4]);
        if not item_id then autoutil.log('AutoBuy', 'Invalid item ID.'); return true; end
        if buy_type ~= 'single' and buy_type ~= 'stack' then autoutil.log('AutoBuy', 'Buy type must be "single" or "stack"'); return true; end
        if not quantity or quantity < 1 then autoutil.log('AutoBuy', 'Quantity must be a positive integer.'); return true; end
        local price, can_buy = get_price(item_id, buy_type == 'stack');
        if not can_buy then autoutil.log('AutoBuy', 'Item not found in price list; use UI to buy at AH-listed price.'); return true; end
        mod.buy_item_direct(item_id, buy_type == 'stack', quantity, price);
        return true;
    end

    if subcmd == 'group' then
        if #args < 2 then autoutil.log('AutoBuy', 'Usage: /automog buy group <Group Name>'); return true; end
        local is_partial = (args[#args] == 'partial');
        local name_end   = is_partial and (#args - 1) or #args;
        local key        = table.concat(args, ' ', 2, name_end):lower();
        local entry = groups_by_key[key];
        if not entry then autoutil.log('AutoBuy', string.format('No group found for "%s".', key)); return true; end
        if not is_partial then
            for _, item in ipairs(entry.list) do
                local item_id = find_item_id_by_name(item.name);
                if not item_id then
                    autoutil.log('AutoBuy', string.format('Aborted: item not found: %s', item.name)); return true;
                end
                local _, can_buy = get_price(item_id, false);
                if not can_buy then
                    autoutil.log('AutoBuy', string.format('Aborted: not on AH: %s', item.name)); return true;
                end
            end
        end
        state.queue = {}; state.waiting = false; state.current_name = nil; state.current_bought = 0;
        state.recipe_key = entry.name;
        autoutil.log('AutoBuy', string.format('Group: %s', entry.name));
        for _, item in ipairs(entry.list) do
            local item_id = find_item_id_by_name(item.name);
            if not item_id then autoutil.log('AutoBuy', string.format('  item not found: %s', item.name));
            else
                local bid_price, can_buy = get_price(item_id, false);
                if not can_buy then autoutil.log('AutoBuy', string.format('  not on AH: %s', item.name));
                else
                    for _ = 1, item.quantity do
                        table.insert(state.queue, { bid=make_bid(item_id, false, bid_price), name=item.name });
                    end
                end
            end
        end
        if #state.queue == 0 then autoutil.log('AutoBuy', 'Nothing to purchase.'); return true; end
        state.status = string.format('Buying group: %s (%d bids)', entry.name, #state.queue);
        autoutil.log('AutoBuy', string.format('Queued %d bid packet(s).', #state.queue));
        send_next();
        return true;
    end

    if subcmd == 'recipe' or subcmd == 'partial' then
        if #args < 4 then
            autoutil.log('AutoBuy', string.format('Usage: /automog buy %s <Recipe> [v<n>] single|stack quantity', subcmd)); return true;
        end
        local explicit_variant = nil; local buy_type_idx = 3;
        if args[3] then
            local v = args[3]:lower():match('^v(%d+)$');
            if v then explicit_variant = tonumber(v); buy_type_idx = 4; end
        end
        if #args < buy_type_idx + 1 then
            autoutil.log('AutoBuy', string.format('Usage: /automog buy %s <Recipe> [v<n>] single|stack quantity', subcmd)); return true;
        end
        local buy_type = args[buy_type_idx]:lower();
        local quantity = tonumber(args[buy_type_idx + 1]);
        if buy_type ~= 'single' and buy_type ~= 'stack' then autoutil.log('AutoBuy', 'Buy type must be "single" or "stack"'); return true; end
        if not quantity or quantity < 1 then autoutil.log('AutoBuy', 'Quantity must be a positive integer'); return true; end
        local key, variants, alias_variant = resolve_recipe(args[2]);
        if not key then autoutil.log('AutoBuy', string.format('No recipe found for "%s".', args[2])); return true; end
        local is_stack = (buy_type == 'stack');
        local quantity_items = is_stack and quantity * 12 or quantity;
        if subcmd == 'recipe' then
            local variant_idx = explicit_variant or alias_variant or nil;
            if variant_idx and (variant_idx < 1 or variant_idx > #variants) then
                autoutil.log('AutoBuy', string.format('"%s" has %d variant(s).', key, #variants)); return true;
            end
            local candidates = variant_idx and { variants[variant_idx] } or variants;
            local recipe, purchases, synths = find_available_recipe(candidates, is_stack, quantity_items);
            if not recipe then autoutil.log('AutoBuy', 'No variant with all ingredients available.'); return true; end
            local total_buys = 0;
            for _, p in ipairs(purchases) do total_buys = total_buys + p.count; end
            if free_inventory_slots() < total_buys then
                autoutil.log('AutoBuy', string.format('Not enough inventory space (%d needed).', total_buys)); return true;
            end
            local checks = {};
            for _, p in ipairs(purchases) do
                table.insert(checks, { item_id=p.item_id, is_stack=p.is_stack, count_needed=p.count, name=p.name });
            end
            start_ah_stock_check(checks, purchases, key, false);
        else -- partial
            local variant_idx = explicit_variant or alias_variant or 1;
            if variant_idx < 1 or variant_idx > #variants then
                autoutil.log('AutoBuy', string.format('"%s" has %d variant(s).', key, #variants)); return true;
            end
            local recipe, purchases, synths = find_partial_recipe(variants[variant_idx], is_stack, quantity_items);
            if not recipe or #purchases == 0 then autoutil.log('AutoBuy', 'No available ingredients.'); return true; end
            local total_buys = 0;
            for _, p in ipairs(purchases) do total_buys = total_buys + p.count; end
            if free_inventory_slots() < total_buys then
                autoutil.log('AutoBuy', string.format('Not enough inventory space (%d needed).', total_buys)); return true;
            end
            local checks = {};
            for _, p in ipairs(purchases) do
                table.insert(checks, { item_id=p.item_id, is_stack=p.is_stack, count_needed=p.count, name=p.name });
            end
            start_ah_stock_check(checks, purchases, key, true);
        end
        return true;
    end

    if subcmd == 'vendor' then
        if #args < 4 then autoutil.log('AutoBuy', 'Usage: /automog buy vendor <Item Name> single|stack quantity'); return true; end
        local quantity = tonumber(args[#args]);
        if not quantity or quantity < 1 then autoutil.log('AutoBuy', 'Quantity must be a positive integer'); return true; end
        local buy_type = args[#args - 1]:lower();
        if buy_type ~= 'single' and buy_type ~= 'stack' then autoutil.log('AutoBuy', 'Buy type must be "single" or "stack"'); return true; end
        local item_name = table.concat(args, ' ', 2, #args - 2);
        if item_name == '' then autoutil.log('AutoBuy', 'Usage: /autobuy vendor "Item Name" single|stack quantity'); return true; end
        local server_id    = autoutil.get_current_target_server_id();
        local target_index = autoutil.get_current_target_index();
        if not server_id or server_id == 0 then autoutil.log('AutoBuy', 'No valid target. Target a vendor NPC first.'); return true; end
        vendor.pending = { display=item_name, name_lc=item_name:lower(), qty=quantity, is_stack=(buy_type=='stack') };
        vendor.cache   = nil;
        vendor.sent_at = os.clock();
        autoutil.log('AutoBuy', string.format('Talking to vendor for: %s x%d (%s)', item_name, quantity, buy_type));
        AddOutgoingPacket(ACTION_OPCODE, make_npc_talk(server_id, target_index):totable());
        return true;
    end

    -- item subcommand
    if #args < 4 then autoutil.log('AutoBuy', 'Usage: /automog buy item <Item Name> single|stack quantity [bid_price]'); return true; end
    local item_name = args[2];
    local buy_type  = args[3]:lower();
    local quantity  = tonumber(args[4]);
    local price_arg = tonumber(args[5]);
    if buy_type ~= 'single' and buy_type ~= 'stack' then autoutil.log('AutoBuy', 'Buy type must be "single" or "stack"'); return true; end
    if not quantity or quantity < 1 then autoutil.log('AutoBuy', 'Quantity must be a positive integer'); return true; end
    local item_id = find_item_id_by_name(item_name);
    if not item_id then autoutil.log('AutoBuy', string.format('Item not found: %s', item_name)); return true; end
    local is_stack = (buy_type == 'stack');
    local bid_price;
    if price_arg then
        bid_price = price_arg;
    else
        local csv_price, can_buy = get_price(item_id, is_stack);
        if csv_price then
            if not can_buy then autoutil.log('AutoBuy', string.format('"%s" not sold as %s on AH.', item_name, buy_type)); return true; end
            bid_price = csv_price;
        else bid_price = 0; end
    end
    if free_inventory_slots() < quantity then
        autoutil.log('AutoBuy', string.format('Not enough inventory space (%d needed).', quantity)); return true;
    end
    state.queue = {}; state.waiting = false; state.current_name = nil; state.current_bought = 0;
    for _ = 1, quantity do
        table.insert(state.queue, { bid=make_bid(item_id, is_stack, bid_price), name=item_name });
    end
    state.status = string.format('Buying %d x %s', quantity, item_name);
    autoutil.log('AutoBuy', string.format('Queued %d bid(s) for %s @ %d gil.', quantity, item_name, bid_price));
    send_next();
    return true;
end

return mod;
