--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local spells = require('spells');
local job_abilities = require('job_abilities');
local autoutil = require('autoutil');

-- ============================================================
-- Vana'diel time
-- ============================================================

local gVanaTime = ashita.memory.find('FFXiMain.dll', 0, 'B0015EC390518B4C24088D4424005068', 0, 0);
if gVanaTime == 0 then
	autoutil.log('AutoEquip', 'WARNING: Vana\'diel time pointer not found - e_time conditions will not work');
end

local function get_vana_time()
	local pointer = ashita.memory.read_uint32(gVanaTime + 0x34);
	local rawTime = ashita.memory.read_uint32(pointer + 0x0C) + 92514960;
	return {
		hour   = math.floor(rawTime / 144) % 24,
		minute = math.floor((rawTime % 144) / 2.4),
	};
end

local autoequip = {};

-- Internal slot name -> canonical XML element tag used in AshitaCast files.
-- ear1/ear2 and ring1/ring2 are the conventional XML names; lear/rear/lring/rring are synonyms.
local SLOT_XML_TAG = {
	main='main',  sub='sub',    range='range', ammo='ammo',
	head='head',  body='body',  hands='hands', legs='legs',  feet='feet',
	neck='neck',  waist='waist',
	lear='ear1',  rear='ear2',  lring='ring1', rring='ring2', back='back',
};
autoequip.SLOT_XML_TAG = SLOT_XML_TAG;

-- Equipment slot name -> slot index for outgoing packet 0x50
-- Order matches FFXI server: main/sub/range/ammo, head, body, hands, legs, feet,
-- neck, waist, ears, rings, back
local SLOT_IDS = {
	main=0,   sub=1,    range=2,  ammo=3,
	head=4,   body=5,   hands=6,  legs=7,   feet=8,
	neck=9,   waist=10,
	lear=11,  ear1=11,
	rear=12,  ear2=12,
	lring=13, ring1=13,
	rring=14, ring2=14,
	back=15,
};

-- Spell element numeric ID -> element name string (used in %ad_element substitution)
local ELEMENT_NAMES = {
	[0]='Fire', [1]='Ice',   [2]='Wind',  [3]='Earth',
	[4]='Lightning', [5]='Water', [6]='Light', [7]='Dark',
};

-- Spell skill numeric ID -> AshitaCast ad_skill string
local SKILL_NAMES = {
	[32]='DivineMagic',
	[33]='HealingMagic',
	[34]='EnhancingMagic',
	[35]='EnfeebllingMagic',
	[36]='ElementalMagic',
	[37]='DarkMagic',
	[38]='Summoning',
	[39]='Ninjutsu',
	[40]='Singing',
	[41]='StringInstrument',
	[42]='WindInstrument',
	[43]='BlueMagic',
	[44]='GeoMancy',
	[45]='Handbell',
};

autoequip.xml_root      = nil;
autoequip.sets_node     = nil;
autoequip.variables     = {};
autoequip.loaded_char   = nil;
autoequip.loaded_job    = nil;
autoequip.load_tried    = false;
autoequip.last_gear       = {};   -- last sent item per slot, for per-slot change detection
autoequip.current_section = nil;  -- section name of the last equip call (e.g. 'idlegear', 'premagic')
autoequip.job_levels      = {};   -- keyed by job index (1=WAR…22=RUN), populated from 0x1B packet

-- ============================================================
-- "Edit target" char/job — when nil, fall back to the local player. When set
-- by the addon's char selector dropdown, every load/save/picker path edits the
-- override target instead of the local char. This lets the editor work on any
-- headless bot owned by the primary while the underlying client is still the
-- primary's game session.
-- ============================================================
autoequip.edit_char_override = nil;
autoequip.edit_job_override  = nil;

-- Local-player char name. Default if no override is set.
function autoequip.get_local_char()
    local party = AshitaCore:GetDataManager():GetParty();
    return (party and party:GetMemberName(0)) or '';
end

-- Local-player job name. Default if no override is set.
function autoequip.get_local_job()
    local party = AshitaCore:GetDataManager():GetParty();
    local idx   = party and party:GetMemberMainJob(0) or 0;
    return autoutil.jobs[idx] or '';
end

-- Authoritative "who is being edited" — used by every load/save/picker path.
-- Returns char + job. If only char_override is set we keep the local player's
-- current job — but typically the dropdown sets both together.
function autoequip.get_edit_target()
    local char = autoequip.edit_char_override
    local job  = autoequip.edit_job_override
    if char == nil or char == '' then char = autoequip.get_local_char() end
    if job  == nil or job  == '' then job  = autoequip.get_local_job()  end
    return char, job
end

function autoequip.set_edit_target(char, job)
    autoequip.edit_char_override = char
    autoequip.edit_job_override  = job
end

-- ============================================================
-- XML Parser
-- ============================================================

-- Find the closing > of a tag, respecting quoted attribute values.
-- This handles attributes like p_tp=">999" or p_hpp="<75" safely.
local function find_tag_end(content, start)
	local pos = start;
	local in_quote = false;
	local quote_char = nil;
	while pos <= #content do
		local c = content:sub(pos, pos);
		if in_quote then
			if c == quote_char then
				in_quote = false;
			end
		else
			if c == '"' or c == "'" then
				in_quote = true;
				quote_char = c;
			elseif c == '>' then
				return pos;
			end
		end
		pos = pos + 1;
	end
	return nil;
end

-- Extract key="value" pairs from a tag body string.
local function parse_attrs(tag_body)
	local attrs = {};
	for key, val in tag_body:gmatch('([%w_]+)%s*=%s*"([^"]*)"') do
		attrs[key] = val;
	end
	return attrs;
end

-- Tokenize XML content into a flat list of tokens.
-- Types: open, close, self, text
local function tokenize(content)
	content = content:gsub('<!%-%-(.-)%-%->', '');  -- strip comments

	local tokens = {};
	local pos = 1;
	local len = #content;

	while pos <= len do
		local lt = content:find('<', pos, true);
		if lt == nil then
			local text = content:sub(pos):match('^%s*(.-)%s*$');
			if text ~= '' then
				table.insert(tokens, {type='text', value=text});
			end
			break;
		end

		if lt > pos then
			local text = content:sub(pos, lt - 1):match('^%s*(.-)%s*$');
			if text ~= '' then
				table.insert(tokens, {type='text', value=text});
			end
		end

		local gt = find_tag_end(content, lt + 1);
		if gt == nil then
			break;
		end

		local inner = content:sub(lt + 1, gt - 1);

		if inner:sub(1, 1) == '/' then
			local tagname = inner:match('^/([%w_]+)');
			if tagname then
				table.insert(tokens, {type='close', tag=tagname});
			end
		elseif inner:sub(-1) == '/' then
			local tagname = inner:match('^([%w_]+)');
			if tagname then
				table.insert(tokens, {type='self', tag=tagname, attrs=parse_attrs(inner)});
			end
		elseif inner:sub(1, 1) ~= '?' then
			local tagname = inner:match('^([%w_]+)');
			if tagname then
				table.insert(tokens, {type='open', tag=tagname, attrs=parse_attrs(inner)});
			end
		end

		pos = gt + 1;
	end

	return tokens;
end

-- Recursively build a node tree starting at the open-tag token at start_pos.
-- Returns (node, next_pos).
local function build_tree(tokens, start_pos)
	local open_tok = tokens[start_pos];
	local node = {tag=open_tok.tag, attrs=open_tok.attrs, children={}, text=''};
	local pos = start_pos + 1;

	while pos <= #tokens do
		local tok = tokens[pos];
		if tok.type == 'close' then
			return node, pos + 1;
		elseif tok.type == 'open' then
			local child, new_pos = build_tree(tokens, pos);
			table.insert(node.children, child);
			pos = new_pos;
		elseif tok.type == 'self' then
			table.insert(node.children, {tag=tok.tag, attrs=tok.attrs, children={}, text=''});
			pos = pos + 1;
		elseif tok.type == 'text' then
			node.text = tok.value;
			pos = pos + 1;
		else
			pos = pos + 1;
		end
	end

	return node, pos;
end

local function parse_xml(content)
	local tokens = tokenize(content);
	for i, tok in ipairs(tokens) do
		if tok.type == 'open' then
			local root, _ = build_tree(tokens, i);
			return root;
		end
	end
	return nil;
end

-- ============================================================
-- Gear set resolution with baseset inheritance
-- ============================================================

local function resolve_set(sets_node, set_name, visited)
	visited = visited or {};
	if visited[set_name] then
		return {};
	end
	visited[set_name] = true;

	local set_node = nil;
	for _, child in ipairs(sets_node.children) do
		if child.tag == 'set' and child.attrs.name == set_name then
			set_node = child;
			break;
		end
	end
	if set_node == nil then
		return {};
	end

	-- Start from baseset, then overlay this set's slots
	local result = {};
	if set_node.attrs.baseset and set_node.attrs.baseset ~= '' then
		local base = resolve_set(sets_node, set_node.attrs.baseset, visited);
		for k, v in pairs(base) do
			result[k] = v;
		end
	end

	for _, slot_node in ipairs(set_node.children) do
		if slot_node.text and slot_node.text ~= '' then
			result[slot_node.tag] = slot_node.text;
		end
	end

	return result;
end

-- ============================================================
-- Condition evaluation
-- ============================================================

-- Match a spell name against an AshitaCast pattern.
-- Supports * wildcard and | OR separator (e.g. "Cure*|Curaga*").
local function match_name_pattern(pattern, name)
	if name == nil then
		return false;
	end
	local lname = name:lower();
	for part in (pattern .. '|'):gmatch('([^|]+)|') do
		part = part:match('^%s*(.-)%s*$');
		if part ~= '' then
			-- Escape Lua magic chars except *, then convert * -> .*
			local lua_pat = '^' .. part:lower()
				:gsub('([%(%)%.%+%-%?%[%]%^%$%%])', '%%%1')
				:gsub('%*', '.*') .. '$';
			if lname:match(lua_pat) then
				return true;
			end
		end
	end
	return false;
end

-- Strip null terminators that C string bindings sometimes leave in Lua strings.
local function clean_str(s)
	if s == nil then return nil; end
	return (s:gsub('%z', ''));
end

-- Equipment slot IDs for eq_ condition keys.
local EQ_SLOT_IDS = {
	eq_main=0,  eq_sub=1,    eq_range=2,  eq_ammo=3,
	eq_head=4,  eq_body=5,   eq_hands=6,  eq_legs=7,  eq_feet=8,
	eq_neck=9,  eq_waist=10,
	eq_lear=11, eq_ear1=11,
	eq_rear=12, eq_ear2=12,
	eq_lring=13, eq_ring1=13,
	eq_rring=14, eq_ring2=14,
	eq_back=15,
};

-- Return the equipped item name for a given slot id, or '' if empty.
local function get_equipped_item_name(slot_id)
	local inv     = AshitaCore:GetDataManager():GetInventory();
	local res_mgr = AshitaCore:GetResourceManager();
	local item    = inv:GetEquippedItem(slot_id);
	if item and item.Id ~= 0 then
		local res = res_mgr:GetItemById(item.Id);
		if res and res.Name then
			return clean_str(tostring(res.Name[0])) or '';
		end
	end
	return '';
end

-- Return lowercase buff name for a given buff ID via resource manager, or nil.
local function get_buff_name(buff_id)
	-- Original used :GetStatusIconById(buff_id).Name to read the status name
	-- off the icon metadata struct — but GetStatusIconById is not exposed in
	-- this Ashita v3 build (confirmed via iconprobe), so it returns nil and
	-- any call would crash on the .Name index. The string-table API is the
	-- right path for buff name lookup — same one automagic.lua uses to
	-- populate partyStatus buff name entries. Language id 2 = English.
	local resmgr = AshitaCore:GetResourceManager();
	if resmgr == nil then return nil; end
	local name = resmgr:GetString('statusnames', buff_id, 2);
	if name == nil or name == '' then return nil; end
	return (clean_str(tostring(name)) or ''):lower();
end

-- Collect all active buff IDs from the player's buff table (handles [0] index).
local function get_all_buffs()
	local buffs = AshitaCore:GetDataManager():GetPlayer():GetBuffs();
	local all = {};
	if buffs[0] ~= nil and buffs[0] > 0 then
		table.insert(all, buffs[0]);
	end
	for _, b in ipairs(buffs) do
		if b > 0 then table.insert(all, b); end
	end
	return all;
end

-- Evaluate a buffactive condition string.
-- Supports numeric IDs, names, xN count suffix, ! negation, and | OR.
local function eval_buffactive(cond_str)
	local all_buffs = get_all_buffs();
	for part in (cond_str .. '|'):gmatch('([^|]+)|') do
		part = part:match('^%s*(.-)%s*$');
		local negated = part:sub(1, 1) == '!';
		if negated then part = part:sub(2); end
		local base, count_str = part:match('^(.+)x(%d+)$');
		local required = 1;
		if base then
			required = tonumber(count_str) or 1;
		else
			base = part;
		end
		local buff_id_num = tonumber(base);
		local base_lower  = base:lower();
		local count = 0;
		for _, b in ipairs(all_buffs) do
			if buff_id_num then
				if b == buff_id_num then count = count + 1; end
			else
				local name = get_buff_name(b);
				if name and name == base_lower then count = count + 1; end
			end
		end
		local result = negated and (count < required) or (count >= required);
		if result then return true; end
	end
	return false;
end

-- Evaluate a numeric condition string against a value.
-- Supports operators < > <= >= = != and | OR, & AND separators.
-- e.g. ">999", "<75", "<6.00|>17.59", ">500&<1000"
local function eval_numeric_cond(cond_str, value)
	if value == nil then return false; end
	for part in (cond_str .. '|'):gmatch('([^|]+)|') do
		local all_true = true;
		for sub in (part .. '&'):gmatch('([^&]+)&') do
			sub = sub:match('^%s*(.-)%s*$');
			local matched = false;
			local op, num_str = sub:match('^([<>=!]+)%s*(.+)$');
			if op and num_str then
				local num = tonumber(num_str);
				if num then
					if     op == '>'            then matched = value >  num;
					elseif op == '<'            then matched = value <  num;
					elseif op == '>='           then matched = value >= num;
					elseif op == '<='           then matched = value <= num;
					elseif op == '=' or op == '==' then matched = value == num;
					elseif op == '!='           then matched = value ~= num;
					end
				end
			else
				local num = tonumber(sub);
				if num then matched = (value == num); end
			end
			if not matched then all_true = false; break; end
		end
		if all_true then return true; end
	end
	return false;
end

-- Evaluate e_time condition against the current Vana'diel time.
-- Time expressed as hour.minute float (e.g. 17.59 = 17:59 Vana'diel).
local function eval_time_cond(cond_str)
	if gVanaTime == 0 then
		return false;
	end
	local t = get_vana_time();
	local current = t.hour + t.minute / 100.0;
	return eval_numeric_cond(cond_str, current);
end

-- Check if a value matches any of the |-separated alternatives in a pattern string (case-insensitive).
local function match_or(pattern, value)
	if value == nil then return false; end
	local lval = tostring(value):lower();
	for part in (pattern .. '|'):gmatch('([^|]+)|') do
		part = part:match('^%s*(.-)%s*$'):lower();
		if part == lval then return true; end
	end
	return false;
end

-- Evaluate all attributes of an <if> or <elseif> node (all must pass = AND).
-- A leading ! on a value negates the result for that attribute (not equal to).
-- buffactive handles its own ! internally; all others are negated at this level.
local function eval_condition(attrs, spell_info, player_info, variables)
	for key, val in pairs(attrs) do
		local negate = (key ~= 'buffactive') and (val:sub(1, 1) == '!');
		local check  = negate and val:sub(2) or val;
		local ok = true;

		-- Action data
		if     key == 'ad_type'  then ok = match_or(check, spell_info.type);
		elseif key == 'ad_name'  then ok = match_name_pattern(check, spell_info.name);
		elseif key == 'ad_skill' then ok = match_or(check, spell_info.skill_name);
		elseif key == 'ad_id'    then ok = eval_numeric_cond(check, spell_info.id);
		elseif key == 'ad_element' then ok = match_or(check, spell_info.element);
		elseif key == 'ad_recast'       then ok = eval_numeric_cond(check, spell_info.recast);
		elseif key == 'ad_casttime'     then ok = eval_numeric_cond(check, spell_info.casttime);
		elseif key == 'ad_mpcost'       then ok = eval_numeric_cond(check, spell_info.mpcost);
		elseif key == 'ad_mpaftercast'  then ok = eval_numeric_cond(check, spell_info.mpaftercast);
		elseif key == 'ad_mppaftercast' then ok = eval_numeric_cond(check, spell_info.mppaftercast);

		-- Player numeric
		elseif key == 'p_hp'  then ok = eval_numeric_cond(check, player_info.hp);
		elseif key == 'p_hpp' then ok = eval_numeric_cond(check, player_info.hpp);
		elseif key == 'p_mp'  then ok = eval_numeric_cond(check, player_info.mp);
		elseif key == 'p_mpp' then ok = eval_numeric_cond(check, player_info.mpp);
		elseif key == 'p_tp'  then ok = eval_numeric_cond(check, player_info.tp);
		elseif key == 'p_hpmax'  then ok = eval_numeric_cond(check, player_info.hpmax);
		elseif key == 'p_mpmax'  then ok = eval_numeric_cond(check, player_info.mpmax);
		elseif key == 'p_joblevel'    then ok = eval_numeric_cond(check, player_info.joblevel);
		elseif key == 'p_subjoblevel' then ok = eval_numeric_cond(check, player_info.subjoblevel);
		elseif key == 'p_attack'  then ok = eval_numeric_cond(check, player_info.attack);
		elseif key == 'p_defense' then ok = eval_numeric_cond(check, player_info.defense);
		elseif key == 'p_fireresist'      then ok = eval_numeric_cond(check, player_info.fireresist);
		elseif key == 'p_iceresist'       then ok = eval_numeric_cond(check, player_info.iceresist);
		elseif key == 'p_windresist'      then ok = eval_numeric_cond(check, player_info.windresist);
		elseif key == 'p_earthresist'     then ok = eval_numeric_cond(check, player_info.earthresist);
		elseif key == 'p_lightningresist' then ok = eval_numeric_cond(check, player_info.lightningresist);
		elseif key == 'p_waterresist'     then ok = eval_numeric_cond(check, player_info.waterresist);
		elseif key == 'p_lightresist'     then ok = eval_numeric_cond(check, player_info.lightresist);
		elseif key == 'p_darkresist'      then ok = eval_numeric_cond(check, player_info.darkresist);

		-- Player string
		elseif key == 'p_status'  then ok = match_or(check, player_info.status);
		elseif key == 'p_mainjob' then ok = match_or(check, player_info.mainjob);
		elseif key == 'p_subjob'  then ok = match_or(check, player_info.subjob);
		elseif key == 'p_job'     then ok = match_or(check, player_info.job);
		elseif key == 'p_name'    then ok = match_or(check, player_info.name);

		-- Environment
		elseif key == 'e_time' then ok = eval_time_cond(check);

		-- Target numeric
		elseif key == 't_hpp'      then ok = eval_numeric_cond(check, player_info.t_hpp);
		elseif key == 't_distance' then ok = eval_numeric_cond(check, player_info.t_distance);
		elseif key == 't_id'       then ok = eval_numeric_cond(check, player_info.t_id);
		elseif key == 't_index'    then ok = eval_numeric_cond(check, player_info.t_index);
		-- Target string
		elseif key == 't_name' then ok = match_or(check, player_info.t_name);
		elseif key == 't_type' then ok = match_or(check, player_info.t_type);

		-- Party
		elseif key == 'pt_inparty' then ok = match_or(check, player_info.pt_inparty);
		elseif key == 'pt_count'   then ok = eval_numeric_cond(check, player_info.pt_count);
		elseif key == 'pt_target'  then ok = match_or(check, player_info.pt_target);

		-- Alliance
		elseif key == 'a_inally' then ok = match_or(check, player_info.a_inally);
		elseif key == 'a_count'  then ok = eval_numeric_cond(check, player_info.a_count);
		elseif key == 'a_target' then ok = match_or(check, player_info.a_target);

		-- Equipment
		elseif EQ_SLOT_IDS[key] ~= nil then
			ok = match_or(check, get_equipped_item_name(EQ_SLOT_IDS[key]));

		-- Pet
		elseif key == 'pet_active'   then ok = match_or(check, player_info.pet_active);
		elseif key == 'pet_hpp'      then ok = eval_numeric_cond(check, player_info.pet_hpp);
		elseif key == 'pet_status'   then ok = match_or(check, player_info.pet_status);
		elseif key == 'pet_name'     then ok = match_or(check, player_info.pet_name);
		elseif key == 'pet_distance' then ok = eval_numeric_cond(check, player_info.pet_distance);

		-- Buff check
		elseif key == 'buffactive' then ok = eval_buffactive(val);

		end

		if negate then ok = not ok; end
		if not ok then return false; end
	end
	return true;
end

-- ============================================================
-- Section processing: walk a <premagic>/<midmagic> node tree,
-- evaluate if/elseif/else chains, and accumulate gear slots.
-- ============================================================

local function process_section(section_node, spell_info, player_info, sets_node, variables)
	local gear = {};

	local function apply(slots)
		for slot, item in pairs(slots) do
			gear[slot] = item;
		end
	end

	local function process_nodes(nodes)
		local idx = 1;
		while idx <= #nodes do
			local node = nodes[idx];
			local tag  = node.tag;

			if tag == 'equip' then
				if node.attrs.set and node.attrs.set ~= '' then
					-- Substitute %ad_* placeholders in the set name (e.g. Staff_%ad_element -> Staff_Fire)
					local set_name = node.attrs.set:gsub('%%ad_element', spell_info.element or '');
					apply(resolve_set(sets_node, set_name, {}));
				else
					-- Inline slot elements: <equip><head>Item Name</head></equip>
					local inline = {};
					for _, slot_node in ipairs(node.children) do
						if slot_node.text and slot_node.text ~= '' then
							inline[slot_node.tag] = slot_node.text;
						end
					end
					apply(inline);
				end
				idx = idx + 1;

			elseif tag == 'if' then
				local cond_met = eval_condition(node.attrs, spell_info, player_info, variables);
				if cond_met then
					process_nodes(node.children);
				end
				idx = idx + 1;

				-- Consume any following elseif/else siblings that belong to this chain
				while idx <= #nodes do
					local nxt = nodes[idx];
					if nxt.tag == 'elseif' then
						if not cond_met then
							cond_met = eval_condition(nxt.attrs, spell_info, player_info, variables);
							if cond_met then
								process_nodes(nxt.children);
							end
						end
						idx = idx + 1;
					elseif nxt.tag == 'else' then
						if not cond_met then
							process_nodes(nxt.children);
						end
						idx = idx + 1;
						break;
					else
						break;
					end
				end

			else
				idx = idx + 1;
			end
		end
	end

	process_nodes(section_node.children);
	return gear;
end

-- ============================================================
-- Inventory lookup: find an item by name across all wearable containers.
-- Returns (inv_index, container_id) or nil.
-- ============================================================

local SEARCH_CONTAINERS = {
	0,   -- Inventory
	8,   -- Wardrobe 1
	10,  -- Wardrobe 2
	11,  -- Wardrobe 3
	12,  -- Wardrobe 4
	13,  -- Wardrobe 5
	14,  -- Wardrobe 6
	15,  -- Wardrobe 7
	16,  -- Wardrobe 8
};

local CONTAINER_NAMES = {
	[0]='Inventory',
	[8]='Wardrobe1', [10]='Wardrobe2', [11]='Wardrobe3', [12]='Wardrobe4',
	[13]='Wardrobe5', [14]='Wardrobe6', [15]='Wardrobe7', [16]='Wardrobe8',
};

-- ============================================================
-- XML serializer (used by save/set_slot)
-- Note: comments and blank lines in the original XML are not preserved after save.
-- ============================================================

local function serialize_node(node, depth)
	depth = depth or 0;
	local ind = string.rep('\t', depth);
	local attr_parts = {};
	if node.attrs then
		for k, v in pairs(node.attrs) do
			table.insert(attr_parts, k .. '="' .. tostring(v) .. '"');
		end
		table.sort(attr_parts);
	end
	local attr_str = #attr_parts > 0 and (' ' .. table.concat(attr_parts, ' ')) or '';

	if #node.children > 0 then
		local out = { ind .. '<' .. node.tag .. attr_str .. '>' };
		for _, child in ipairs(node.children) do
			table.insert(out, serialize_node(child, depth + 1));
		end
		table.insert(out, ind .. '</' .. node.tag .. '>');
		return table.concat(out, '\n');
	elseif node.text and node.text ~= '' then
		return ind .. '<' .. node.tag .. attr_str .. '>' .. node.text .. '</' .. node.tag .. '>';
	else
		return ind .. '<' .. node.tag .. attr_str .. '/>';
	end
end

-- ============================================================
-- Public API
-- ============================================================

-- Dump all items in each container to the console. Useful for diagnosing container ID issues.
function autoequip.debug_inventory()
	local inv     = AshitaCore:GetDataManager():GetInventory();
	local res_mgr = AshitaCore:GetResourceManager();
	for _, container_id in ipairs(SEARCH_CONTAINERS) do
		local max = inv:GetContainerMax(container_id);
		autoutil.log('AutoEquip', string.format('container=%d (%s) max=%d',
			container_id, CONTAINER_NAMES[container_id] or '?', max));
		for i = 1, max do
			local item = inv:GetItem(container_id, i);
			if item and item.Id ~= 0 then
				local res = res_mgr:GetItemById(item.Id);
				local name = res and res.Name and clean_str(res.Name[0]) or '?';
				autoutil.log('AutoEquip', string.format('  [%d] id=%d count=%d name="%s"',
					i, item.Id, item.Count or 0, name));
			end
		end
	end
end

-- Apply a parsed XML body to autoequip's in-memory state. Returns true on
-- success, false (with an error logged) when <sets> is missing or parse failed.
local function apply_parsed_body(char_name, job_name, content)
	local root = parse_xml(content or '');
	if root == nil then
		autoutil.log('AutoEquip', 'Failed to parse XML');
		return false;
	end
	local sets_node = nil;
	for _, child in ipairs(root.children) do
		if child.tag == 'sets' then
			sets_node = child;
			break;
		end
	end
	if sets_node == nil then
		autoutil.log('AutoEquip', 'No <sets> element found in XML');
		return false;
	end

	local variables = {};
	for _, child in ipairs(root.children) do
		if child.tag == 'variables' then
			for _, var_node in ipairs(child.children) do
				if var_node.tag == 'var' and var_node.attrs.name then
					variables[var_node.attrs.name] = var_node.text or '0';
				end
			end
		end
	end

	autoequip.xml_root    = root;
	autoequip.sets_node   = sets_node;
	autoequip.variables   = variables;
	autoequip.loaded_char = char_name;
	autoequip.loaded_job  = job_name;
	return true;
end

-- Synchronous server-side fetch over loopback HTTP. Server is the source
-- of truth for configs; the addon no longer reads from the local Ashita
-- install. Invokes callback(success) inline once the response is parsed.
-- The callback is optional — callers that don't care about the result can
-- omit. The signature stays callback-shaped (rather than returning success)
-- to preserve the call sites that already expect to fire continuation work
-- when the load completes (e.g. gear_tab.reload_config rebuilding sets).
function autoequip.load(char_name, job_name, callback)
	autoequip.load_tried = true;
	if char_name == nil or char_name == '' or job_name == nil or job_name == '' then
		if callback then callback(false) end
		return;
	end
	local filename = string.format('%s_%s', char_name, job_name);
	local http     = require('http_client');
	-- Async GET: schedule the fetch, react in the callback once the response
	-- arrives (on a later frame). The main thread isn't blocked, so the
	-- FFXI client keeps pumping keepalives and the UI keeps rendering.
	http.get('/configs/equip/' .. filename, function(code, body, _, err)
		if code == nil then
			autoutil.log('AutoEquip', string.format('HTTP fetch failed for %s: %s', filename, tostring(err)));
			if callback then callback(false) end
			return;
		end
		if code == 404 then
			autoutil.log('AutoEquip', string.format('No equip config on server for %s', filename));
			if callback then callback(false) end
			return;
		end
		if code ~= 200 or body == nil or body == '' then
			autoutil.log('AutoEquip', string.format('Server returned %s for %s', tostring(code), filename));
			if callback then callback(false) end
			return;
		end
		local ok = apply_parsed_body(char_name, job_name, body);
		if ok then
			autoutil.log('AutoEquip', string.format('Loaded %s', filename));
			-- (Gearlock visual lock is now applied server-side on
			-- onGameIn — see modules/singleplayer/bots/ai_equip_swap.lua.
			-- No client-side packet to ship here anymore.)
		end
		if callback then callback(ok) end
	end);
end

-- Mutate the in-memory tree only. Persistence happens via the addon's Save
-- button → 0x180 → server. The in-memory tree is the working copy until the
-- next fetch via autoequip.load.
function autoequip.set_slot(set_name, slot_key, item_name)
	if not autoequip.sets_node then return; end
	local xml_tag = SLOT_XML_TAG[slot_key] or slot_key;
	for _, set_node in ipairs(autoequip.sets_node.children) do
		if set_node.tag == 'set' and set_node.attrs and set_node.attrs.name == set_name then
			local found = false;
			for _, slot_node in ipairs(set_node.children) do
				if slot_node.tag == xml_tag or slot_node.tag == slot_key then
					slot_node.text = item_name or '';
					found = true;
					break;
				end
			end
			if not found and item_name and item_name ~= '' then
				table.insert(set_node.children, {tag=xml_tag, attrs={}, children={}, text=item_name});
			end
			break;
		end
	end
end

-- Remove a slot entry from a set entirely (drops the <head>/<body>/... node
-- from the set's children). Resolution treats a missing slot the same as
-- an empty one, but actually deleting the node keeps the saved XML tidy.
-- No-op when the set or slot doesn't exist.
function autoequip.remove_slot(set_name, slot_key)
	if not autoequip.sets_node then return; end
	local xml_tag = SLOT_XML_TAG[slot_key] or slot_key;
	for _, set_node in ipairs(autoequip.sets_node.children) do
		if set_node.tag == 'set' and set_node.attrs and set_node.attrs.name == set_name then
			for i, slot_node in ipairs(set_node.children) do
				if slot_node.tag == xml_tag or slot_node.tag == slot_key then
					table.remove(set_node.children, i);
					return;
				end
			end
			return;
		end
	end
end

-- Reload the current character/job config (useful after an /autoequip reload command).
function autoequip.reload()
	if autoequip.loaded_char and autoequip.loaded_job then
		autoequip.load_tried = false;
		autoequip.load(autoequip.loaded_char, autoequip.loaded_job);
	end
end

-- Attempt to load the config for the currently logged-in character if not already loaded.
-- Called automatically by every public equip function.
local function ensure_loaded()
	if autoequip.xml_root ~= nil then
		return;
	end
	if autoequip.load_tried then
		return;
	end

	-- Edit-target aware: honor the dropdown override if set.
	local char_name, job_name = autoequip.get_edit_target();
	if not char_name or char_name == '' or not job_name or job_name == '' then
		autoequip.load_tried = true;
		return;
	end

	autoequip.load(char_name, job_name);
end

-- Find a top-level section node (e.g. 'premagic', 'midmagic') in the loaded XML.
local function get_section(name)
	if autoequip.xml_root == nil then
		return nil;
	end
	for _, child in ipairs(autoequip.xml_root.children) do
		if child.tag == name then
			return child;
		end
	end
	return nil;
end

-- Build a spell_info table from a spell ID using the spells data.
local function build_spell_info(spell_id)
	local spell = spells[spell_id];
	if spell == nil then return nil; end
	local mpcost = spell.mp_cost or 0;
	local curmp  = AshitaCore:GetDataManager():GetParty():GetMemberCurrentMP(0);
	return {
		id           = spell.id,
		name         = spell.en,
		type         = spell.type,
		skill_name   = SKILL_NAMES[spell.skill],
		element      = ELEMENT_NAMES[spell.element],
		recast       = spell.recast,
		casttime     = spell.cast_time,
		mpcost       = mpcost,
		mpaftercast  = curmp - mpcost,
		mppaftercast = AshitaCore:GetDataManager():GetParty():GetMemberCurrentMPP(0),
	};
end

-- Build a spell_info table from a job ability ID using the job_abilities data.
local function build_ability_info(ability_id)
	local ability = job_abilities[ability_id];
	if ability == nil then
		return nil;
	end
	return {
		name       = ability.en,
		type       = ability.type and ability.type:lower() or 'jobability',
		skill_name = nil,
		element    = nil,
	};
end

-- Build a player_info table from live game data.
local function build_player_info()
	local party      = AshitaCore:GetDataManager():GetParty();
	local player     = AshitaCore:GetDataManager():GetPlayer();
	local entity_mgr = AshitaCore:GetDataManager():GetEntity();
	local player_idx = party:GetMemberTargetIndex(0);
	local status_id  = entity_mgr:GetStatus(player_idx);

	local status_str;
	if     status_id == 1              then status_str = 'engaged';
	elseif status_id == 33             then status_str = 'resting';
	elseif status_id == 2 or status_id == 3 then status_str = 'dead';
	else                                    status_str = 'idle';
	end

	local mainJobIdx = party:GetMemberMainJob(0);
	local subJobIdx  = party:GetMemberSubJob(0);
	local mainJobStr = autoutil.jobs[mainJobIdx] and autoutil.jobs[mainJobIdx]:lower() or 'unknown';
	local subJobStr  = autoutil.jobs[subJobIdx]  and autoutil.jobs[subJobIdx]:lower()  or '';
	local jobStr     = subJobStr ~= '' and (mainJobStr .. '/' .. subJobStr) or mainJobStr;

	-- Party / alliance counts and target membership
	local pt_count = 0;
	local a_count  = 0;
	for i = 0, 5 do
		local nm = party:GetMemberName(i);
		if nm and nm ~= '' then pt_count = pt_count + 1; end
	end
	for i = 0, 17 do
		local nm = party:GetMemberName(i);
		if nm and nm ~= '' then a_count = a_count + 1; end
	end

	-- Current selected target info
	local tgt_api  = AshitaCore:GetDataManager():GetTarget();
	local tgt_idx  = tgt_api:GetTargetIndex();
	local tgt_sid  = tgt_api:GetTargetServerId();
	local tgt_ent  = (tgt_idx ~= nil and tgt_idx ~= 0) and GetEntity(tgt_idx) or nil;
	local t_hpp, t_distance, t_id, t_index, t_name, t_type;
	local pt_target, a_target = false, false;
	if tgt_ent ~= nil then
		t_hpp      = tgt_ent.HealthPercent;
		t_distance = math.sqrt(tgt_ent.Distance);
		t_id       = tgt_sid;
		t_index    = tgt_idx;
		t_name     = clean_str(tostring(tgt_ent.Name or ''));
		local flags = tgt_ent.SpawnFlags;
		if     bit.band(flags, 0x0200) ~= 0 then t_type = 'self';
		elseif bit.band(flags, 0x0001) ~= 0 then t_type = 'pc';
		elseif bit.band(flags, 0x0002) ~= 0 then t_type = 'npc';
		elseif bit.band(flags, 0x0010) ~= 0 then t_type = 'monster';
		else                                      t_type = 'unknown'; end
		for i = 0, 5 do
			if party:GetMemberServerId(i) == tgt_sid then
				pt_target = true; a_target = true; break;
			end
		end
		if not a_target then
			for i = 6, 17 do
				if party:GetMemberServerId(i) == tgt_sid then a_target = true; break; end
			end
		end
	end

	-- Pet info (via player entity's PetTargetIndex)
	local self_ent = GetEntity(player_idx);
	local pet_ent  = (self_ent and self_ent.PetTargetIndex ~= 0) and GetEntity(self_ent.PetTargetIndex) or nil;
	local pet_active, pet_hpp, pet_status_str, pet_name, pet_distance;
	if pet_ent then
		pet_active = 'true';
		pet_hpp    = pet_ent.HealthPercent;
		pet_name   = clean_str(tostring(pet_ent.Name or ''));
		pet_distance = math.sqrt(pet_ent.Distance);
		local ps = pet_ent.Status;
		if     ps == 1              then pet_status_str = 'engaged';
		elseif ps == 33             then pet_status_str = 'resting';
		elseif ps == 2 or ps == 3  then pet_status_str = 'dead';
		else                             pet_status_str = 'idle'; end
	else
		pet_active = 'false';
	end

	return {
		-- Player numeric
		hp          = party:GetMemberCurrentHP(0),
		hpp         = party:GetMemberCurrentHPP(0),
		mp          = party:GetMemberCurrentMP(0),
		mpp         = party:GetMemberCurrentMPP(0),
		tp          = party:GetMemberCurrentTP(0),
		hpmax       = player:GetHealthMax(),
		mpmax       = player:GetManaMax(),
		joblevel    = party:GetMemberMainJobLevel(0),
		subjoblevel = party:GetMemberSubJobLvl(0),
		attack      = player:GetAttack(),
		defense     = player:GetDefense(),
		fireresist      = player:GetResist(0),
		iceresist       = player:GetResist(1),
		windresist      = player:GetResist(2),
		earthresist     = player:GetResist(3),
		lightningresist = player:GetResist(4),
		waterresist     = player:GetResist(5),
		lightresist     = player:GetResist(6),
		darkresist      = player:GetResist(7),
		-- Player string
		status  = status_str,
		mainjob = mainJobStr,
		subjob  = subJobStr,
		job     = jobStr,
		name    = clean_str(tostring(party:GetMemberName(0) or '')),
		-- Party / alliance
		pt_count   = pt_count,
		a_count    = a_count,
		pt_inparty = pt_count > 1 and 'true' or 'false',
		a_inally   = a_count > 6  and 'true' or 'false',
		pt_target  = pt_target and 'true' or 'false',
		a_target   = a_target  and 'true' or 'false',
		-- Target
		t_hpp      = t_hpp,
		t_distance = t_distance,
		t_id       = t_id,
		t_index    = t_index,
		t_name     = t_name,
		t_type     = t_type,
		-- Pet
		pet_active   = pet_active,
		pet_hpp      = pet_hpp,
		pet_status   = pet_status_str,
		pet_name     = pet_name,
		pet_distance = pet_distance,
	};
end

local EQUIP_BY_ID_OPCODE    = 0x173;
local EQUIP_BY_ID_RESULT    = 0x174;

-- Entries sent in the most recent 0x173 packet; committed to last_gear on 0x174 response.
local pending_equip = nil;

-- Send a single 0x173 equip-by-id packet for all slots whose item has changed.
-- The server searches its own authoritative inventory for each item ID, so no
-- client-side inventory walk is needed.  last_gear is NOT updated here; it is
-- updated when the 0x174 response arrives (success or failure).
-- Returns a table of slot->item for every slot queued in the packet.
local function send_equip_packets(gear)
	local changed = {};
	local entries = {};
	local res_mgr = AshitaCore:GetResourceManager();

	-- If body is changing, clear head from last_gear so it gets re-sent.
	-- Some body pieces block the head slot; the server silently rejects the head
	-- equip packet while they're on, leaving last_gear out of sync with reality.
	if gear['body'] ~= nil and gear['body'] ~= autoequip.last_gear['body'] then
		autoequip.last_gear['head'] = nil;
	end

	for slot_name, item_name in pairs(gear) do
		if autoequip.last_gear[slot_name] ~= item_name then
			local slot_id = SLOT_IDS[slot_name];
			if slot_id ~= nil then
				local res = res_mgr:GetItemByName(item_name, 1);
				if res then
					table.insert(entries, { item_id = res.ItemId, slot_id = slot_id, slot_name = slot_name, item_name = item_name });
				else
					autoutil.log('AutoEquip', string.format('Unknown item: "%s" (slot: %s)', item_name, slot_name));
				end
			else
				autoutil.log('AutoEquip', string.format('Unknown slot name: "%s"', slot_name));
			end
		end
	end

	if #entries == 0 then return changed; end

	-- Body MUST be sorted first so the server processes it before head.
	-- Some body pieces set m_EquipBlock on the head slot (e.g. certain capes/mantles
	-- that visually replace the head model).  The server processes entries in array
	-- order, so if head arrives before body the head equip hits the old body's
	-- m_EquipBlock state and may succeed or fail incorrectly.  By guaranteeing body
	-- is entry[1] we ensure the new body's block state is established before head
	-- is evaluated.  main(0) < sub(1) already sorts correctly by slot_id ascending,
	-- so body is the only slot that needs an explicit priority override.
	table.sort(entries, function(a, b)
		local pa = (a.slot_id == SLOT_IDS.body) and 0 or 1;
		local pb = (b.slot_id == SLOT_IDS.body) and 0 or 1;
		if pa ~= pb then return pa < pb; end
		return a.slot_id < b.slot_id;
	end);

	-- Build 0x173 packet: 4-byte header + 4-byte (count + padding) + up to 16 x 4-byte entries
	local count = math.min(#entries, 16);
	local bytes  = {};
	for i = 1, 4 + 4 + 16 * 4 do bytes[i] = 0; end
	bytes[1] = 0x73; bytes[2] = 0x01;  -- opcode 0x173 LE
	bytes[5] = count;
	for i = 1, count do
		local base = 8 + (i - 1) * 4;
		local e    = entries[i];
		bytes[base + 1] = e.item_id % 256;
		bytes[base + 2] = math.floor(e.item_id / 256) % 256;
		bytes[base + 3] = e.slot_id;
	end

	pending_equip = entries;
	AddOutgoingPacket(EQUIP_BY_ID_OPCODE, bytes);

	-- Return the queued slots so callers know what was attempted.
	for i = 1, count do
		changed[entries[i].slot_name] = entries[i].item_name;
	end
	return changed;
end

-- Result codes from 0x174 response (mirror server-side enum in 0x174_equip_by_id_result.h)
local EQUIP_RESULT_SUCCESS  = 0;
local EQUIP_RESULT_NOTFOUND = 1;
local EQUIP_RESULT_BLOCKED  = 2;
local EQUIP_RESULT_NOOP     = 3;

function autoequip.on_incoming_packet(id, size, data)
	if id ~= EQUIP_BY_ID_RESULT then return false; end
	if pending_equip == nil then return false; end

	local ok, err = xpcall(function()
		-- Packet body: byte 5 = Count, bytes 6-8 = padding, bytes 9+ = Results[0..Count-1]
		local count = struct.unpack('B', data, 5);

		for i = 1, math.min(count, #pending_equip) do
			local e      = pending_equip[i];
			local result = struct.unpack('B', data, 8 + i);

			-- Server processed this entry regardless of outcome; update last_gear so we
			-- don't re-send it next tick.  The only exception would be NOTFOUND, but
			-- we still record it to avoid hammering the server for a missing item.
			autoequip.last_gear[e.slot_name] = e.item_name;

			if result == EQUIP_RESULT_NOTFOUND then
				autoutil.log('AutoEquip', string.format('Item not found: "%s" (slot: %s)', e.item_name, e.slot_name));
			elseif result == EQUIP_RESULT_BLOCKED then
				autoutil.log('AutoEquip', string.format('Equip blocked by game mechanic: "%s" -> %s', e.item_name, e.slot_name));
			end
			-- EQUIP_RESULT_SUCCESS (0) and EQUIP_RESULT_NOOP (3) need no log.
		end

		pending_equip = nil;
	end, debug.traceback);
	if not ok then autoutil.log('AutoEquip', 'on_incoming_packet error: ' .. tostring(err)); end
	return false;
end

local function format_changed(changed)
	local parts = {};
	for slot, item in pairs(changed) do
		table.insert(parts, slot .. '=' .. item);
	end
	table.sort(parts);
	return #parts > 0 and table.concat(parts, ', ') or 'none';
end

local EMPTY_SPELL_INFO = {id=nil, name=nil, type=nil, skill_name=nil, element=nil, recast=nil, casttime=nil, mpcost=nil, mpaftercast=nil, mppaftercast=nil};

local function equip_section(section_name, spell_info)
	ensure_loaded();
	if autoequip.xml_root == nil then
		autoutil.log('AutoEquip', string.format('%s: xml not loaded (char=%s)', section_name, tostring(autoequip.loaded_char)));
		return;
	end
	local section = get_section(section_name);
	if section == nil then
		autoutil.log('AutoEquip', string.format('%s: section not found in xml', section_name));
		return;
	end
	local gear = process_section(section, spell_info, build_player_info(), autoequip.sets_node, autoequip.variables);
	local changed = send_equip_packets(gear);
	autoequip.current_section = section_name;
	if next(changed) ~= nil then
		autoutil.log('AutoEquip', string.format('%s changed: %s', section_name, format_changed(changed)));
	end
end

function autoequip.tick()
	if autoequip.current_section ~= 'idlegear' then return; end
	equip_section('idlegear', EMPTY_SPELL_INFO);
end

function autoequip.equip_premagic(spell_id)
	local spell_info = build_spell_info(spell_id);
	if spell_info == nil then
		autoutil.log('AutoEquip', string.format('premagic: unknown spell_id=%s', tostring(spell_id)));
		return;
	end
	equip_section('premagic', spell_info);
end

function autoequip.equip_midcast(spell_id)
	local spell_info = build_spell_info(spell_id);
	if spell_info == nil then
		autoutil.log('AutoEquip', string.format('midcast: unknown spell_id=%s', tostring(spell_id)));
		return;
	end
	equip_section('midmagic', spell_info);
end

function autoequip.equip_idlegear()
	equip_section('idlegear', EMPTY_SPELL_INFO);
end

function autoequip.equip_weaponskill(ws_id)
	equip_section('weaponskill', EMPTY_SPELL_INFO);
end

function autoequip.equip_preranged()
	equip_section('preranged', EMPTY_SPELL_INFO);
end

function autoequip.equip_midranged()
	equip_section('midranged', EMPTY_SPELL_INFO);
end

function autoequip.equip_petskill(skill_id)
	equip_section('petskill', EMPTY_SPELL_INFO);
end

function autoequip.equip_petspell(spell_id)
	equip_section('petspell', build_spell_info(spell_id) or EMPTY_SPELL_INFO);
end

function autoequip.equip_jobability(ability_id)
	local ability_info = build_ability_info(ability_id);
	if ability_info == nil then
		autoutil.log('AutoEquip', string.format('jobability: unknown ability_id=%s', tostring(ability_id)));
		return;
	end
	equip_section('jobability', ability_info);
end

-- The client-side gearlock lockstyle send (send_lockstyle_set +
-- apply_gearlock_lockstyle) used to live here. It's been retired —
-- the visual lock is now driven entirely server-side from
-- modules/singleplayer/bots/ai_equip_swap.lua's apply_gearlock_lockstyle,
-- triggered by the xi.player.onGameIn hook. Reasons for the move:
--   * Server already owns the XML on disk and the applyStyleLock binding;
--     the round-trip through the addon's lazy XML fetch was just ceremony.
--   * No more "open the addon UI once before gearlock kicks in."
--   * One source of truth — primary and headless go through the same
--     server-side resolver and binding.
-- equip_gearlock here is now just the real-equip path for the explicit
-- "park me" action; visual locking happens server-side automatically.
function autoequip.equip_gearlock()
	equip_section('gearlock', EMPTY_SPELL_INFO);
end

function autoequip.equip_set(set_name)
	ensure_loaded();
	if autoequip.xml_root == nil then
		autoutil.log('AutoEquip', 'set: xml not loaded');
		return;
	end
	if autoequip.sets_node == nil then
		autoutil.log('AutoEquip', 'set: no sets node');
		return;
	end
	local gear = resolve_set(autoequip.sets_node, set_name, {});
	if next(gear) == nil then
		autoutil.log('AutoEquip', string.format('set: unknown set "%s"', set_name));
		return;
	end
	local changed = send_equip_packets(gear);
	if next(changed) ~= nil then
		autoutil.log('AutoEquip', string.format('set %s: %s', set_name, format_changed(changed)));
	end
end

autoequip.resolve_set = resolve_set;

function autoequip.handle_command(args)
	if args[1] ~= '/autoequip' then return false; end
	-- Only claim subcommands the lib actually owns. Anything else (show, reload,
	-- nil, ...) falls through so the addon's own handler can run — without this,
	-- /autoequip show was getting eaten by the usage-line branch below.
	if args[2] == 'set' and args[3] ~= nil then
		autoequip.equip_set(args[3]);
		return true;
	end
	return false;
end

-- Expose the serializer for tabs that need to ship the whole document back
-- to the server via PUT /configs/equip/<file>. Indentation matches what
-- the server wrote (the original load path), so a fetch → no-op-edit →
-- save round-trip is byte-stable.
autoequip.serialize_node = serialize_node;
autoequip.parse_xml      = parse_xml;

-- Serialize the entire in-memory XML document into a string suitable for
-- the body of a PUT. Returns nil if no file is loaded. The XML declaration
-- line matches the one the legacy server-side set_subtree_equip writer
-- used, so existing files won't churn header bytes on first save.
function autoequip.serialize_full()
    if autoequip.xml_root == nil then return nil; end
    return '<?xml version="1.0" encoding="utf-8" standalone="yes"?>\n'
         .. serialize_node(autoequip.xml_root, 0);
end

return autoequip;
