--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local autoutil = require('autoutil');

local mod = {};

local queue         = {};
local waiting       = false;
local pendingSlot   = nil;
local waitTimeoutMs = 0;
local WAIT_TIMEOUT  = 5000;

mod.state = {
    queue_count = 0,
    waiting     = false,
    active      = false,
    status      = 'Idle',
};

local function send_drop(entry)
    autoutil.log('AutoDrop', string.format('Dropping %s x%d (slot %d)', entry.name, entry.count, entry.index));
    local packet = struct.pack('HHLBBBB', 0x028, 0x03, entry.count, 0, entry.index, 0, 0);
    AddOutgoingPacket(0x028, packet:totable());
    waiting       = true;
    pendingSlot   = entry.index;
    waitTimeoutMs = autoutil.get_ms_since_epoch() + WAIT_TIMEOUT;
    mod.state.waiting     = true;
    mod.state.active      = true;
    mod.state.status      = string.format('Dropping %s...', entry.name);
end

function mod.on_incoming_packet(id, size, data)
    if id == 0x020 and waiting then
        local category  = struct.unpack('B', data, 0x0E + 1);
        local itemIndex = struct.unpack('B', data, 0x0F + 1);
        if category == 0 and itemIndex == pendingSlot then
            waiting = false; pendingSlot = nil;
            mod.state.waiting = false;
        end
    end
    if id == 0x01E and waiting then
        local category  = struct.unpack('B', data, 0x08 + 1);
        local itemIndex = struct.unpack('B', data, 0x09 + 1);
        if category == 0 and itemIndex == pendingSlot then
            waiting = false; pendingSlot = nil;
            mod.state.waiting = false;
        end
    end
    return false;
end

function mod.on_render()
    if #queue == 0 then
        if mod.state.status ~= 'Idle' and not waiting then
            mod.state.active      = false;
            mod.state.status      = 'Idle';
            mod.state.queue_count = 0;
        end
        return;
    end
    local ok, err = xpcall(function()
        if waiting then
            if autoutil.get_ms_since_epoch() > waitTimeoutMs then
                autoutil.log('AutoDrop', string.format('Timed out waiting for slot %d, continuing.', tostring(pendingSlot)));
                waiting = false; pendingSlot = nil;
                mod.state.waiting = false;
            end
            return;
        end
        local entry = table.remove(queue, 1);
        mod.state.queue_count = #queue;
        send_drop(entry);
    end, debug.traceback);
    if not ok then autoutil.log('AutoDrop', 'render error: ' .. tostring(err)); end
end

-- entries = { {index=slot, count=n, name=str}, ... } resolved from inv_cache by caller
function mod.queue_drops(entries)
    queue = {}; waiting = false; pendingSlot = nil;
    for _, e in ipairs(entries) do
        table.insert(queue, e);
    end
    mod.state.queue_count = #queue;
    if #queue > 0 then
        mod.state.active = true;
        mod.state.status = string.format('Queued %d stack(s)', #queue);
        autoutil.log('AutoDrop', string.format('Queued %d item(s) to drop.', #queue));
    end
end

function mod.on_command(args)
    if not autoutil.unlocked then
        autoutil.log('AutoDrop', 'Not unlocked.');
        return true;
    end
    if args[1] == 'stop' then
        local n = #queue;
        queue = {}; waiting = false; pendingSlot = nil;
        mod.state.queue_count = 0;
        mod.state.waiting     = false;
        mod.state.active      = false;
        mod.state.status      = 'Idle';
        autoutil.log('AutoDrop', string.format('Stopped. Cleared %d pending drop(s).', n));
        return true;
    end
    autoutil.log('AutoDrop', 'Usage: /automog drop <item name>  |  /automog drop stop');
    return true;
end

return mod;
