--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

local autoutil = require('autoutil');

local mod = {};

local AUTOSCROLL_OPCODE = 0x165;
local AUTOSCROLL_RESULT = 0x166;
local BYTE_COUNT  = 5;
local BYTE_SPELLS = 9;

mod.state = {
    status = 'Idle',
};

local function make_packet()
    return struct.pack('HHBBBB', AUTOSCROLL_OPCODE, 0, 0, 0, 0, 0);
end

function mod.learn()
    if not autoutil.unlocked then
        autoutil.log('AutoScroll', 'Not unlocked.');
        return;
    end
    autoutil.log('AutoScroll', 'Learning scrolls...');
    mod.state.status = 'Learning...';
    AddOutgoingPacket(AUTOSCROLL_OPCODE, make_packet():totable());
end

function mod.on_incoming_packet(id, size, data)
    if id ~= AUTOSCROLL_RESULT then return false; end
    if not autoutil.unlocked then return false; end
    local ok, err = xpcall(function()
        local count = struct.unpack('B', data, BYTE_COUNT);
        if count == 0 then
            autoutil.log('AutoScroll', 'No scrolls learned.');
            mod.state.status = 'Done (0 learned)';
            return;
        end
        autoutil.log('AutoScroll', string.format('Learned %d spell(s):', count));
        for i = 0, count - 1 do
            local spell_id = struct.unpack('H', data, BYTE_SPELLS + i * 2);
            local spell    = AshitaCore:GetResourceManager():GetSpellById(spell_id);
            local name     = spell and spell.Name[1] or string.format('Spell #%d', spell_id);
            autoutil.log('AutoScroll', string.format('  - %s', name));
        end
        mod.state.status = string.format('Done (%d learned)', count);
    end, debug.traceback);
    if not ok then autoutil.log('AutoScroll', 'packet error: ' .. tostring(err)); end
    return false;
end

function mod.on_command(cmd)
    local args = cmd:args();
    if #args == 0 or args[1]:lower() ~= '/autoscroll' then return false; end
    mod.learn();
    return true;
end

return mod;
