-- AI Generated
-- Hardcoded scroll data extracted from LandSandBoat items.csv.
-- Keys match spell.en values in spells.lua exactly.
-- item_id is the in-game item ID. Price is looked up at runtime from items.csv.

return {
    -- White Magic / Healing
    ["Cure"]              = {item_id=4609},
    ["Cure II"]           = {item_id=4610},
    ["Cure III"]          = {item_id=4611},
    ["Cure IV"]           = {item_id=4612},
    ["Cure V"]            = {item_id=4613},
    ["Curaga"]            = {item_id=4615},
    ["Curaga II"]         = {item_id=4616},
    ["Curaga III"]        = {item_id=4617},
    ["Curaga IV"]         = {item_id=4618},
    ["Raise"]             = {item_id=4620},
    ["Raise II"]          = {item_id=4621},
    ["Raise III"]         = {item_id=4748},
    ["Poisona"]           = {item_id=4622},
    ["Paralyna"]          = {item_id=4623},
    ["Blindna"]           = {item_id=4624},
    ["Silena"]            = {item_id=4625},
    ["Stona"]             = {item_id=4626},
    ["Viruna"]            = {item_id=4627},
    ["Cursna"]            = {item_id=4628},
    ["Cura"]              = {item_id=4701},
    ["Sacrifice"]         = {item_id=4702},
    ["Esuna"]             = {item_id=4703},
    ["Holy"]              = {item_id=4629},

    -- White Magic / Enfeebling
    ["Dia"]               = {item_id=4631},
    ["Dia II"]            = {item_id=4632},
    ["Dia III"]           = {item_id=4633},
    ["Diaga"]             = {item_id=4641},
    ["Slow"]              = {item_id=4664},
    ["Paralyze"]          = {item_id=4666},
    ["Silence"]           = {item_id=4667},
    ["Repose"]            = {item_id=4721},

    -- White Magic / Divine
    ["Banish"]            = {item_id=4636},
    ["Banish II"]         = {item_id=4637},
    ["Banish III"]        = {item_id=4638},
    ["Banishga"]          = {item_id=4646},
    ["Banishga II"]       = {item_id=4647},
    ["Flash"]             = {item_id=4720},

    -- White Magic / Enhancing
    ["Protect"]           = {item_id=4651},
    ["Protect II"]        = {item_id=4652},
    ["Protect III"]       = {item_id=4653},
    ["Protect IV"]        = {item_id=4654},
    ["Protectra"]         = {item_id=4733},
    ["Protectra II"]      = {item_id=4734},
    ["Protectra III"]     = {item_id=4735},
    ["Protectra IV"]      = {item_id=4736},
    ["Protectra V"]       = {item_id=4737},
    ["Shell"]             = {item_id=4656},
    ["Shell II"]          = {item_id=4657},
    ["Shell III"]         = {item_id=4658},
    ["Shell IV"]          = {item_id=4659},
    ["Shellra"]           = {item_id=4738},
    ["Shellra II"]        = {item_id=4739},
    ["Shellra III"]       = {item_id=4740},
    ["Shellra IV"]        = {item_id=4741},
    ["Shellra V"]         = {item_id=4742},
    ["Blink"]             = {item_id=4661},
    ["Stoneskin"]         = {item_id=4662},
    ["Aquaveil"]          = {item_id=4663},
    ["Haste"]             = {item_id=4665},
    ["Auspice"]           = {item_id=4704},
    ["Phalanx"]           = {item_id=4714},
    ["Reprisal"]          = {item_id=4715},
    ["Regen"]             = {item_id=4716},
    ["Regen II"]          = {item_id=4718},
    ["Regen III"]         = {item_id=4719},
    ["Refresh"]           = {item_id=4717},
    ["Erase"]             = {item_id=4751},
    ["Reraise"]           = {item_id=4743},
    ["Reraise II"]        = {item_id=4749},
    ["Reraise III"]       = {item_id=4750},
    ["Invisible"]         = {item_id=4744},
    ["Sneak"]             = {item_id=4745},
    ["Deodorize"]         = {item_id=4746},
    ["Enfire"]            = {item_id=4708},
    ["Enblizzard"]        = {item_id=4709},
    ["Enaero"]            = {item_id=4710},
    ["Enstone"]           = {item_id=4711},
    ["Enthunder"]         = {item_id=4712},
    ["Enwater"]           = {item_id=4713},
    ["Enfire II"]         = {item_id=4722},
    ["Enblizzard II"]     = {item_id=4723},
    ["Enaero II"]         = {item_id=4724},
    ["Enstone II"]        = {item_id=4725},
    ["Enthunder II"]      = {item_id=4726},
    ["Enwater II"]        = {item_id=4727},

    -- White Magic / Bar-spells
    ["Barfire"]           = {item_id=4668},
    ["Barblizzard"]       = {item_id=4669},
    ["Baraero"]           = {item_id=4670},
    ["Barstone"]          = {item_id=4671},
    ["Barthunder"]        = {item_id=4672},
    ["Barwater"]          = {item_id=4673},
    ["Barfira"]           = {item_id=4674},
    ["Barblizzara"]       = {item_id=4675},
    ["Baraera"]           = {item_id=4676},
    ["Barstonra"]         = {item_id=4677},
    ["Barthundra"]        = {item_id=4678},
    ["Barwatera"]         = {item_id=4679},
    ["Barsleep"]          = {item_id=4680},
    ["Barpoison"]         = {item_id=4681},
    ["Barparalyze"]       = {item_id=4682},
    ["Barblind"]          = {item_id=4683},
    ["Barsilence"]        = {item_id=4684},
    ["Barpetrify"]        = {item_id=4685},
    ["Barvirus"]          = {item_id=4686},
    ["Barsleepra"]        = {item_id=4694},
    ["Barpoisonra"]       = {item_id=4695},
    ["Barparalyzra"]      = {item_id=4696},
    ["Barblindra"]        = {item_id=4697},
    ["Barsilencera"]      = {item_id=4698},
    ["Barpetra"]          = {item_id=4699},
    ["Barvira"]           = {item_id=4700},

    -- White Magic / Teleport & Recall
    ["Teleport-Holla"]    = {item_id=4730},
    ["Teleport-Dem"]      = {item_id=4731},
    ["Teleport-Mea"]      = {item_id=4732},
    ["Teleport-Yhoat"]    = {item_id=4728},
    ["Teleport-Altep"]    = {item_id=4729},
    ["Teleport-Vahzl"]    = {item_id=4747},
    ["Recall-Jugner"]     = {item_id=4687},
    ["Recall-Pashh"]      = {item_id=4688},
    ["Recall-Meriph"]     = {item_id=4689},

    -- Black Magic / Elemental
    ["Fire"]              = {item_id=4752},
    ["Fire II"]           = {item_id=4753},
    ["Fire III"]          = {item_id=4754},
    ["Fire IV"]           = {item_id=4755},
    ["Blizzard"]          = {item_id=4757},
    ["Blizzard II"]       = {item_id=4758},
    ["Blizzard III"]      = {item_id=4759},
    ["Blizzard IV"]       = {item_id=4760},
    ["Aero"]              = {item_id=4762},
    ["Aero II"]           = {item_id=4763},
    ["Aero III"]          = {item_id=4764},
    ["Aero IV"]           = {item_id=4765},
    ["Stone"]             = {item_id=4767},
    ["Stone II"]          = {item_id=4768},
    ["Stone III"]         = {item_id=4769},
    ["Stone IV"]          = {item_id=4770},
    ["Thunder"]           = {item_id=4772},
    ["Thunder II"]        = {item_id=4773},
    ["Thunder III"]       = {item_id=4774},
    ["Thunder IV"]        = {item_id=4775},
    ["Water"]             = {item_id=4777},
    ["Water II"]          = {item_id=4778},
    ["Water III"]         = {item_id=4779},
    ["Water IV"]          = {item_id=4780},
    ["Firaga"]            = {item_id=4782},
    ["Firaga II"]         = {item_id=4783},
    ["Firaga III"]        = {item_id=4784},
    ["Blizzaga"]          = {item_id=4787},
    ["Blizzaga II"]       = {item_id=4788},
    ["Blizzaga III"]      = {item_id=4789},
    ["Aeroga"]            = {item_id=4792},
    ["Aeroga II"]         = {item_id=4793},
    ["Aeroga III"]        = {item_id=4794},
    ["Stonega"]           = {item_id=4797},
    ["Stonega II"]        = {item_id=4798},
    ["Stonega III"]       = {item_id=4799},
    ["Thundaga"]          = {item_id=4802},
    ["Thundaga II"]       = {item_id=4803},
    ["Thundaga III"]      = {item_id=4804},
    ["Waterga"]           = {item_id=4807},
    ["Waterga II"]        = {item_id=4808},
    ["Waterga III"]       = {item_id=4809},
    ["Flare"]             = {item_id=4812},
    ["Flare II"]          = {item_id=4813},
    ["Freeze"]            = {item_id=4814},
    ["Freeze II"]         = {item_id=4815},
    ["Tornado"]           = {item_id=4816},
    ["Tornado II"]        = {item_id=4817},
    ["Quake"]             = {item_id=4818},
    ["Quake II"]          = {item_id=4819},
    ["Burst"]             = {item_id=4820},
    ["Burst II"]          = {item_id=4821},
    ["Flood"]             = {item_id=4822},
    ["Flood II"]          = {item_id=4823},

    -- Black Magic / Enfeebling
    ["Gravity"]           = {item_id=4824},
    ["Poison"]            = {item_id=4828},
    ["Poison II"]         = {item_id=4829},
    ["Poisonga"]          = {item_id=4833},
    ["Poisonga II"]       = {item_id=4834},
    ["Bio"]               = {item_id=4838},
    ["Bio II"]            = {item_id=4839},
    ["Bio III"]           = {item_id=4840},
    ["Burn"]              = {item_id=4843},
    ["Frost"]             = {item_id=4844},
    ["Choke"]             = {item_id=4845},
    ["Rasp"]              = {item_id=4846},
    ["Shock"]             = {item_id=4847},
    ["Drown"]             = {item_id=4848},
    ["Sleep"]             = {item_id=4861},
    ["Sleep II"]          = {item_id=4867},
    ["Sleepga"]           = {item_id=4881},
    ["Sleepga II"]        = {item_id=4882},
    ["Blind"]             = {item_id=4862},
    ["Blind II"]          = {item_id=4884},
    ["Bind"]              = {item_id=4866},
    ["Stun"]              = {item_id=4860},
    ["Dispel"]            = {item_id=4868},
    ["Distract"]          = {item_id=4912},
    ["Frazzle"]           = {item_id=4914},

    -- Black Magic / Dark
    ["Drain"]             = {item_id=4853},
    ["Drain II"]          = {item_id=4854},
    ["Aspir"]             = {item_id=4855},
    ["Absorb-STR"]        = {item_id=4874},
    ["Absorb-DEX"]        = {item_id=4875},
    ["Absorb-VIT"]        = {item_id=4876},
    ["Absorb-AGI"]        = {item_id=4877},
    ["Absorb-INT"]        = {item_id=4878},
    ["Absorb-MND"]        = {item_id=4879},
    ["Absorb-CHR"]        = {item_id=4880},
    ["Absorb-TP"]         = {item_id=4883},
    ["Absorb-ACC"]        = {item_id=4886},
    ["Dread Spikes"]      = {item_id=4885},

    -- Black Magic / Enhancing
    ["Blaze Spikes"]      = {item_id=4857},
    ["Ice Spikes"]        = {item_id=4858},
    ["Shock Spikes"]      = {item_id=4859},

    -- Black Magic / Warp / Escape
    ["Warp"]              = {item_id=4869},
    ["Warp II"]           = {item_id=4870},
    ["Escape"]            = {item_id=4871},
    ["Tractor"]           = {item_id=4872},
    ["Retrace"]           = {item_id=4873},

    -- RDM / SCH
    ["Flurry"]            = {item_id=5104},

    -- Summoner Pacts (Spirits)
    ["Fire Spirit"]       = {item_id=4896},
    ["Ice Spirit"]        = {item_id=4897},
    ["Air Spirit"]        = {item_id=4898},
    ["Earth Spirit"]      = {item_id=4899},
    ["Thunder Spirit"]    = {item_id=4900},
    ["Water Spirit"]      = {item_id=4901},
    ["Light Spirit"]      = {item_id=4902},
    ["Dark Spirit"]       = {item_id=4903},

    -- Ninjutsu
    ["Katon: Ichi"]       = {item_id=4928},
    ["Katon: Ni"]         = {item_id=4929},
    ["Katon: San"]        = {item_id=4930},
    ["Hyoton: Ichi"]      = {item_id=4931},
    ["Hyoton: Ni"]        = {item_id=4932},
    ["Hyoton: San"]       = {item_id=4933},
    ["Huton: Ichi"]       = {item_id=4934},
    ["Huton: Ni"]         = {item_id=4935},
    ["Huton: San"]        = {item_id=4936},
    ["Doton: Ichi"]       = {item_id=4937},
    ["Doton: Ni"]         = {item_id=4938},
    ["Doton: San"]        = {item_id=4939},
    ["Raiton: Ichi"]      = {item_id=4940},
    ["Raiton: Ni"]        = {item_id=4941},
    ["Raiton: San"]       = {item_id=4942},
    ["Suiton: Ichi"]      = {item_id=4943},
    ["Suiton: Ni"]        = {item_id=4944},
    ["Suiton: San"]       = {item_id=4945},
    ["Utsusemi: Ichi"]    = {item_id=4946},
    ["Utsusemi: Ni"]      = {item_id=4947},
    ["Jubaku: Ichi"]      = {item_id=4949},
    ["Hojo: Ichi"]        = {item_id=4952},
    ["Hojo: Ni"]          = {item_id=4953},
    ["Kurayami: Ichi"]    = {item_id=4955},
    ["Kurayami: Ni"]      = {item_id=4956},
    ["Dokumori: Ichi"]    = {item_id=4958},
    ["Tonko: Ichi"]       = {item_id=4961},
    ["Tonko: Ni"]         = {item_id=4962},
    ["Monomi: Ichi"]      = {item_id=4964},

    -- Bard Songs
    ["Foe Requiem"]          = {item_id=4976},
    ["Foe Requiem II"]       = {item_id=4977},
    ["Foe Requiem III"]      = {item_id=4978},
    ["Foe Requiem IV"]       = {item_id=4979},
    ["Foe Requiem V"]        = {item_id=4980},
    ["Foe Requiem VI"]       = {item_id=4981},
    ["Horde Lullaby"]        = {item_id=4984},
    ["Foe Lullaby"]          = {item_id=5071},
    ["Army's Paeon"]         = {item_id=4986},
    ["Army's Paeon II"]      = {item_id=4987},
    ["Army's Paeon III"]     = {item_id=4988},
    ["Army's Paeon IV"]      = {item_id=4989},
    ["Army's Paeon V"]       = {item_id=4990},
    ["Mage's Ballad"]        = {item_id=4994},
    ["Mage's Ballad II"]     = {item_id=4995},
    ["Knight's Minne"]       = {item_id=4997},
    ["Knight's Minne II"]    = {item_id=4998},
    ["Knight's Minne III"]   = {item_id=4999},
    ["Knight's Minne IV"]    = {item_id=5000},
    ["Valor Minuet"]         = {item_id=5002},
    ["Valor Minuet II"]      = {item_id=5003},
    ["Valor Minuet III"]     = {item_id=5004},
    ["Valor Minuet IV"]      = {item_id=5005},
    ["Sword Madrigal"]       = {item_id=5007},
    ["Blade Madrigal"]       = {item_id=5008},
    ["Hunter's Prelude"]     = {item_id=5009},
    ["Archer's Prelude"]     = {item_id=5010},
    ["Sheepfoe Mambo"]       = {item_id=5011},
    ["Dragonfoe Mambo"]      = {item_id=5012},
    ["Fowl Aubade"]          = {item_id=5013},
    ["Herb Pastoral"]        = {item_id=5014},
    ["Shining Fantasia"]     = {item_id=5016},
    ["Scop's Operetta"]      = {item_id=5017},
    ["Puppet's Operetta"]    = {item_id=5018},
    ["Gold Capriccio"]       = {item_id=5020},
    ["Warding Round"]        = {item_id=5022},
    ["Goblin Gavotte"]       = {item_id=5023},
    ["Advancing March"]      = {item_id=5027},
    ["Victory March"]        = {item_id=5028},
    ["Battlefield Elegy"]    = {item_id=5029},
    ["Carnage Elegy"]        = {item_id=5030},
    ["Sinewy Etude"]         = {item_id=5032},
    ["Dextrous Etude"]       = {item_id=5033},
    ["Vivacious Etude"]      = {item_id=5034},
    ["Quick Etude"]          = {item_id=5035},
    ["Learned Etude"]        = {item_id=5036},
    ["Spirited Etude"]       = {item_id=5037},
    ["Enchanting Etude"]     = {item_id=5038},
    ["Herculean Etude"]      = {item_id=5039},
    ["Uncanny Etude"]        = {item_id=5040},
    ["Vital Etude"]          = {item_id=5041},
    ["Swift Etude"]          = {item_id=5042},
    ["Sage Etude"]           = {item_id=5043},
    ["Logical Etude"]        = {item_id=5044},
    ["Bewitching Etude"]     = {item_id=5045},
    ["Fire Carol"]           = {item_id=5046},
    ["Ice Carol"]            = {item_id=5047},
    ["Wind Carol"]           = {item_id=5048},
    ["Earth Carol"]          = {item_id=5049},
    ["Lightning Carol"]      = {item_id=5050},
    ["Water Carol"]          = {item_id=5051},
    ["Light Carol"]          = {item_id=5052},
    ["Dark Carol"]           = {item_id=5053},
    ["Fire Threnody"]        = {item_id=5062},
    ["Ice Threnody"]         = {item_id=5063},
    ["Wind Threnody"]        = {item_id=5064},
    ["Earth Threnody"]       = {item_id=5065},
    ["Ltng. Threnody"]       = {item_id=5066},
    ["Water Threnody"]       = {item_id=5067},
    ["Light Threnody"]       = {item_id=5068},
    ["Dark Threnody"]        = {item_id=5069},
    ["Magic Finale"]         = {item_id=5070},
    ["Goddess's Hymnus"]     = {item_id=5072},
    ["Chocobo Mazurka"]      = {item_id=5073},
    ["Maiden's Virelai"]     = {item_id=5074},
    ["Raptor Mazurka"]       = {item_id=5075},
    ["Foe Sirvente"]         = {item_id=5076},
    ["Adventurer's Dirge"]   = {item_id=5077},
};
