--[[
                                                        ___________________________________________
                                      __              |                                           |
                                   _/  /=\            |   There be dragons here!                 |
           )=) )=) )=)          __/ \_/   |           |                                           |
          / / / / / /          /   (o)    |           |   Be warned reader, this was entirely     |
  ~fire~ < < < < < <     _____/     \____|           |   generated by AI!                        |
          \ \ \ \ \ \   /     \    /\    \            |                                           |
           )=) )=) )=) /  /~~\ \  /  \   \           |   Including the dragon!                   |
                      /  / ^^ \/\/    \   \           |___________________________________________|
                     |  /              \   |
                     | / ,    __        \  |
                  /\/|/ /\___/  \     /\/\ |
                 /  (  /        /\   /    \|
                /   |\/    /\  /  \_/|
               /    |/\   /  \/     |
              /   __|  \_/    \_____|
    _________/  _/
   /____________/   ^   ^   ^   ^
                   / \ / \ / \ / \    <- tail spines
]]--

_addon.author  = 'Nate';
_addon.name    = 'AutoWarp';
_addon.version = '1.0';

require 'common';
local autoutil = require('autoutil');

-- ============================================================
-- Custom C2S 0x168: warp a player or enemy to sender's position.
-- Intercepts /warp client-side (client eats /warp before sending
-- any packet, so we must handle it here).
--
-- Usage: /warp player <name>
--        /warp enemy <name>   (underscores treated as spaces)
-- ============================================================

local SUBCMD_PLAYER = 0;
local SUBCMD_ENEMY  = 1;

ashita.register_event('load', function()
    autoutil.tag = 'AutoWarp';
    autoutil.send_request_server_ident();
end);

ashita.register_event('incoming_packet', function(id, size, data)
    if id == 0x150 then
        autoutil.check_for_server_ident(id, size, data);
    end
    return false;
end);

ashita.register_event('command', function(cmd, nType)
    local args = cmd:args();
    if args[1] ~= '/autowarp' then return false; end

    if not autoutil.unlocked then
        autoutil.log('AutoWarp', 'Not unlocked (waiting for server ident).');
        return true;
    end

    local subcmd_str = args[2];
    if subcmd_str ~= 'player' and subcmd_str ~= 'enemy' then
        autoutil.log('AutoWarp', 'Usage: /autowarp player <name> | /autowarp enemy <name>');
        return true;
    end

    if #args < 3 then
        autoutil.log('AutoWarp', 'Usage: /autowarp player <name> | /autowarp enemy <name>');
        return true;
    end

    local name_parts = {};
    for i = 3, #args do
        name_parts[#name_parts + 1] = args[i];
    end
    local target_name = table.concat(name_parts, ' '):gsub('_', ' ');

    if #target_name == 0 or #target_name > 23 then
        autoutil.log('AutoWarp', 'Name must be 1-23 characters.');
        return true;
    end

    local subcmd = (subcmd_str == 'player') and SUBCMD_PLAYER or SUBCMD_ENEMY;
    autoutil.send_warp(subcmd, target_name);
    return true;
end);
